// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/crud/v1/analytics.proto

package crudv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDailyStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int32                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyStatsRequest) Reset() {
	*x = GetDailyStatsRequest{}
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyStatsRequest) ProtoMessage() {}

func (x *GetDailyStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyStatsRequest.ProtoReflect.Descriptor instead.
func (*GetDailyStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_crud_v1_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetDailyStatsRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type DailyStat struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Date              string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD
	TotalTransactions int64                  `protobuf:"varint,2,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	FraudCount        int64                  `protobuf:"varint,3,opt,name=fraud_count,json=fraudCount,proto3" json:"fraud_count,omitempty"`
	FraudRate         float64                `protobuf:"fixed64,4,opt,name=fraud_rate,json=fraudRate,proto3" json:"fraud_rate,omitempty"`
	TotalAmount       float64                `protobuf:"fixed64,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	AvgZScore         float64                `protobuf:"fixed64,6,opt,name=avg_z_score,json=avgZScore,proto3" json:"avg_z_score,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DailyStat) Reset() {
	*x = DailyStat{}
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyStat) ProtoMessage() {}

func (x *DailyStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyStat.ProtoReflect.Descriptor instead.
func (*DailyStat) Descriptor() ([]byte, []int) {
	return file_proto_crud_v1_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *DailyStat) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyStat) GetTotalTransactions() int64 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *DailyStat) GetFraudCount() int64 {
	if x != nil {
		return x.FraudCount
	}
	return 0
}

func (x *DailyStat) GetFraudRate() float64 {
	if x != nil {
		return x.FraudRate
	}
	return 0
}

func (x *DailyStat) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *DailyStat) GetAvgZScore() float64 {
	if x != nil {
		return x.AvgZScore
	}
	return 0
}

type GetDailyStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*DailyStat           `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyStatsResponse) Reset() {
	*x = GetDailyStatsResponse{}
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyStatsResponse) ProtoMessage() {}

func (x *GetDailyStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyStatsResponse.ProtoReflect.Descriptor instead.
func (*GetDailyStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_crud_v1_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GetDailyStatsResponse) GetStats() []*DailyStat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetTransactionDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int32                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionDetailsRequest) Reset() {
	*x = GetTransactionDetailsRequest{}
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionDetailsRequest) ProtoMessage() {}

func (x *GetTransactionDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_crud_v1_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetTransactionDetailsRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *GetTransactionDetailsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TransactionDetail struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	RecordId                string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	UserId                  string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt               *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsTrainEligible         bool                   `protobuf:"varint,4,opt,name=is_train_eligible,json=isTrainEligible,proto3" json:"is_train_eligible,omitempty"`
	IsPreFraud              bool                   `protobuf:"varint,5,opt,name=is_pre_fraud,json=isPreFraud,proto3" json:"is_pre_fraud,omitempty"`
	Amount                  float64                `protobuf:"fixed64,6,opt,name=amount,proto3" json:"amount,omitempty"`
	IsFraudulent            bool                   `protobuf:"varint,7,opt,name=is_fraudulent,json=isFraudulent,proto3" json:"is_fraudulent,omitempty"`
	FraudType               string                 `protobuf:"bytes,8,opt,name=fraud_type,json=fraudType,proto3" json:"fraud_type,omitempty"`
	IsOffHoursTxn           bool                   `protobuf:"varint,9,opt,name=is_off_hours_txn,json=isOffHoursTxn,proto3" json:"is_off_hours_txn,omitempty"`
	MerchantRiskScore       int32                  `protobuf:"varint,10,opt,name=merchant_risk_score,json=merchantRiskScore,proto3" json:"merchant_risk_score,omitempty"`
	Velocity_24H            int32                  `protobuf:"varint,11,opt,name=velocity_24h,json=velocity24h,proto3" json:"velocity_24h,omitempty"`
	AmountToAvgRatio_30D    float64                `protobuf:"fixed64,12,opt,name=amount_to_avg_ratio_30d,json=amountToAvgRatio30d,proto3" json:"amount_to_avg_ratio_30d,omitempty"`
	BalanceVolatilityZScore float64                `protobuf:"fixed64,13,opt,name=balance_volatility_z_score,json=balanceVolatilityZScore,proto3" json:"balance_volatility_z_score,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TransactionDetail) Reset() {
	*x = TransactionDetail{}
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionDetail) ProtoMessage() {}

func (x *TransactionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionDetail.ProtoReflect.Descriptor instead.
func (*TransactionDetail) Descriptor() ([]byte, []int) {
	return file_proto_crud_v1_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionDetail) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *TransactionDetail) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TransactionDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TransactionDetail) GetIsTrainEligible() bool {
	if x != nil {
		return x.IsTrainEligible
	}
	return false
}

func (x *TransactionDetail) GetIsPreFraud() bool {
	if x != nil {
		return x.IsPreFraud
	}
	return false
}

func (x *TransactionDetail) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionDetail) GetIsFraudulent() bool {
	if x != nil {
		return x.IsFraudulent
	}
	return false
}

func (x *TransactionDetail) GetFraudType() string {
	if x != nil {
		return x.FraudType
	}
	return ""
}

func (x *TransactionDetail) GetIsOffHoursTxn() bool {
	if x != nil {
		return x.IsOffHoursTxn
	}
	return false
}

func (x *TransactionDetail) GetMerchantRiskScore() int32 {
	if x != nil {
		return x.MerchantRiskScore
	}
	return 0
}

func (x *TransactionDetail) GetVelocity_24H() int32 {
	if x != nil {
		return x.Velocity_24H
	}
	return 0
}

func (x *TransactionDetail) GetAmountToAvgRatio_30D() float64 {
	if x != nil {
		return x.AmountToAvgRatio_30D
	}
	return 0
}

func (x *TransactionDetail) GetBalanceVolatilityZScore() float64 {
	if x != nil {
		return x.BalanceVolatilityZScore
	}
	return 0
}

type GetTransactionDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*TransactionDetail   `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionDetailsResponse) Reset() {
	*x = GetTransactionDetailsResponse{}
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionDetailsResponse) ProtoMessage() {}

func (x *GetTransactionDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_crud_v1_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *GetTransactionDetailsResponse) GetTransactions() []*TransactionDetail {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type GetRecentAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentAlertsRequest) Reset() {
	*x = GetRecentAlertsRequest{}
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentAlertsRequest) ProtoMessage() {}

func (x *GetRecentAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentAlertsRequest.ProtoReflect.Descriptor instead.
func (*GetRecentAlertsRequest) Descriptor() ([]byte, []int) {
	return file_proto_crud_v1_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *GetRecentAlertsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Alert struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	RecordId                string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	UserId                  string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt               *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Amount                  float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	IsFraudulent            bool                   `protobuf:"varint,5,opt,name=is_fraudulent,json=isFraudulent,proto3" json:"is_fraudulent,omitempty"`
	FraudType               string                 `protobuf:"bytes,6,opt,name=fraud_type,json=fraudType,proto3" json:"fraud_type,omitempty"`
	MerchantRiskScore       int32                  `protobuf:"varint,7,opt,name=merchant_risk_score,json=merchantRiskScore,proto3" json:"merchant_risk_score,omitempty"`
	Velocity_24H            int32                  `protobuf:"varint,8,opt,name=velocity_24h,json=velocity24h,proto3" json:"velocity_24h,omitempty"`
	AmountToAvgRatio_30D    float64                `protobuf:"fixed64,9,opt,name=amount_to_avg_ratio_30d,json=amountToAvgRatio30d,proto3" json:"amount_to_avg_ratio_30d,omitempty"`
	BalanceVolatilityZScore float64                `protobuf:"fixed64,10,opt,name=balance_volatility_z_score,json=balanceVolatilityZScore,proto3" json:"balance_volatility_z_score,omitempty"`
	ComputedRiskScore       int32                  `protobuf:"varint,11,opt,name=computed_risk_score,json=computedRiskScore,proto3" json:"computed_risk_score,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_proto_crud_v1_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *Alert) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *Alert) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Alert) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Alert) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Alert) GetIsFraudulent() bool {
	if x != nil {
		return x.IsFraudulent
	}
	return false
}

func (x *Alert) GetFraudType() string {
	if x != nil {
		return x.FraudType
	}
	return ""
}

func (x *Alert) GetMerchantRiskScore() int32 {
	if x != nil {
		return x.MerchantRiskScore
	}
	return 0
}

func (x *Alert) GetVelocity_24H() int32 {
	if x != nil {
		return x.Velocity_24H
	}
	return 0
}

func (x *Alert) GetAmountToAvgRatio_30D() float64 {
	if x != nil {
		return x.AmountToAvgRatio_30D
	}
	return 0
}

func (x *Alert) GetBalanceVolatilityZScore() float64 {
	if x != nil {
		return x.BalanceVolatilityZScore
	}
	return 0
}

func (x *Alert) GetComputedRiskScore() int32 {
	if x != nil {
		return x.ComputedRiskScore
	}
	return 0
}

type GetRecentAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentAlertsResponse) Reset() {
	*x = GetRecentAlertsResponse{}
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentAlertsResponse) ProtoMessage() {}

func (x *GetRecentAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentAlertsResponse.ProtoReflect.Descriptor instead.
func (*GetRecentAlertsResponse) Descriptor() ([]byte, []int) {
	return file_proto_crud_v1_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *GetRecentAlertsResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

type GetOverviewMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOverviewMetricsRequest) Reset() {
	*x = GetOverviewMetricsRequest{}
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOverviewMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOverviewMetricsRequest) ProtoMessage() {}

func (x *GetOverviewMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOverviewMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetOverviewMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_crud_v1_analytics_proto_rawDescGZIP(), []int{9}
}

type GetOverviewMetricsResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	TotalRecords            int64                  `protobuf:"varint,1,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
	FraudRecords            int64                  `protobuf:"varint,2,opt,name=fraud_records,json=fraudRecords,proto3" json:"fraud_records,omitempty"`
	FraudRate               float64                `protobuf:"fixed64,3,opt,name=fraud_rate,json=fraudRate,proto3" json:"fraud_rate,omitempty"`
	UniqueUsers             int64                  `protobuf:"varint,4,opt,name=unique_users,json=uniqueUsers,proto3" json:"unique_users,omitempty"`
	MinTransactionTimestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=min_transaction_timestamp,json=minTransactionTimestamp,proto3" json:"min_transaction_timestamp,omitempty"`
	MaxTransactionTimestamp *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=max_transaction_timestamp,json=maxTransactionTimestamp,proto3" json:"max_transaction_timestamp,omitempty"`
	MinCreatedAt            *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=min_created_at,json=minCreatedAt,proto3" json:"min_created_at,omitempty"`
	MaxCreatedAt            *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=max_created_at,json=maxCreatedAt,proto3" json:"max_created_at,omitempty"`
	TotalAmount             float64                `protobuf:"fixed64,9,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	FraudAmount             float64                `protobuf:"fixed64,10,opt,name=fraud_amount,json=fraudAmount,proto3" json:"fraud_amount,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetOverviewMetricsResponse) Reset() {
	*x = GetOverviewMetricsResponse{}
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOverviewMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOverviewMetricsResponse) ProtoMessage() {}

func (x *GetOverviewMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOverviewMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetOverviewMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_crud_v1_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *GetOverviewMetricsResponse) GetTotalRecords() int64 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

func (x *GetOverviewMetricsResponse) GetFraudRecords() int64 {
	if x != nil {
		return x.FraudRecords
	}
	return 0
}

func (x *GetOverviewMetricsResponse) GetFraudRate() float64 {
	if x != nil {
		return x.FraudRate
	}
	return 0
}

func (x *GetOverviewMetricsResponse) GetUniqueUsers() int64 {
	if x != nil {
		return x.UniqueUsers
	}
	return 0
}

func (x *GetOverviewMetricsResponse) GetMinTransactionTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.MinTransactionTimestamp
	}
	return nil
}

func (x *GetOverviewMetricsResponse) GetMaxTransactionTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.MaxTransactionTimestamp
	}
	return nil
}

func (x *GetOverviewMetricsResponse) GetMinCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MinCreatedAt
	}
	return nil
}

func (x *GetOverviewMetricsResponse) GetMaxCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MaxCreatedAt
	}
	return nil
}

func (x *GetOverviewMetricsResponse) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *GetOverviewMetricsResponse) GetFraudAmount() float64 {
	if x != nil {
		return x.FraudAmount
	}
	return 0
}

type GetDatasetFingerprintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatasetFingerprintRequest) Reset() {
	*x = GetDatasetFingerprintRequest{}
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatasetFingerprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatasetFingerprintRequest) ProtoMessage() {}

func (x *GetDatasetFingerprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatasetFingerprintRequest.ProtoReflect.Descriptor instead.
func (*GetDatasetFingerprintRequest) Descriptor() ([]byte, []int) {
	return file_proto_crud_v1_analytics_proto_rawDescGZIP(), []int{11}
}

type TableFingerprint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	MaxCreatedAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=max_created_at,json=maxCreatedAt,proto3" json:"max_created_at,omitempty"`
	MaxTimestamp  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=max_timestamp,json=maxTimestamp,proto3" json:"max_timestamp,omitempty"`
	MaxId         int64                  `protobuf:"varint,4,opt,name=max_id,json=maxId,proto3" json:"max_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableFingerprint) Reset() {
	*x = TableFingerprint{}
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableFingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableFingerprint) ProtoMessage() {}

func (x *TableFingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableFingerprint.ProtoReflect.Descriptor instead.
func (*TableFingerprint) Descriptor() ([]byte, []int) {
	return file_proto_crud_v1_analytics_proto_rawDescGZIP(), []int{12}
}

func (x *TableFingerprint) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TableFingerprint) GetMaxCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MaxCreatedAt
	}
	return nil
}

func (x *TableFingerprint) GetMaxTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.MaxTimestamp
	}
	return nil
}

func (x *TableFingerprint) GetMaxId() int64 {
	if x != nil {
		return x.MaxId
	}
	return 0
}

type GetDatasetFingerprintResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GeneratedRecords *TableFingerprint      `protobuf:"bytes,1,opt,name=generated_records,json=generatedRecords,proto3" json:"generated_records,omitempty"`
	FeatureSnapshots *TableFingerprint      `protobuf:"bytes,2,opt,name=feature_snapshots,json=featureSnapshots,proto3" json:"feature_snapshots,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetDatasetFingerprintResponse) Reset() {
	*x = GetDatasetFingerprintResponse{}
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatasetFingerprintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatasetFingerprintResponse) ProtoMessage() {}

func (x *GetDatasetFingerprintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatasetFingerprintResponse.ProtoReflect.Descriptor instead.
func (*GetDatasetFingerprintResponse) Descriptor() ([]byte, []int) {
	return file_proto_crud_v1_analytics_proto_rawDescGZIP(), []int{13}
}

func (x *GetDatasetFingerprintResponse) GetGeneratedRecords() *TableFingerprint {
	if x != nil {
		return x.GeneratedRecords
	}
	return nil
}

func (x *GetDatasetFingerprintResponse) GetFeatureSnapshots() *TableFingerprint {
	if x != nil {
		return x.FeatureSnapshots
	}
	return nil
}

type GetFeatureSampleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SampleSize    int32                  `protobuf:"varint,1,opt,name=sample_size,json=sampleSize,proto3" json:"sample_size,omitempty"`
	Stratify      bool                   `protobuf:"varint,2,opt,name=stratify,proto3" json:"stratify,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeatureSampleRequest) Reset() {
	*x = GetFeatureSampleRequest{}
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeatureSampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeatureSampleRequest) ProtoMessage() {}

func (x *GetFeatureSampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeatureSampleRequest.ProtoReflect.Descriptor instead.
func (*GetFeatureSampleRequest) Descriptor() ([]byte, []int) {
	return file_proto_crud_v1_analytics_proto_rawDescGZIP(), []int{14}
}

func (x *GetFeatureSampleRequest) GetSampleSize() int32 {
	if x != nil {
		return x.SampleSize
	}
	return 0
}

func (x *GetFeatureSampleRequest) GetStratify() bool {
	if x != nil {
		return x.Stratify
	}
	return false
}

type FeatureSample struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	RecordId                string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	IsFraudulent            bool                   `protobuf:"varint,2,opt,name=is_fraudulent,json=isFraudulent,proto3" json:"is_fraudulent,omitempty"`
	Velocity_24H            float64                `protobuf:"fixed64,3,opt,name=velocity_24h,json=velocity24h,proto3" json:"velocity_24h,omitempty"`
	AmountToAvgRatio_30D    float64                `protobuf:"fixed64,4,opt,name=amount_to_avg_ratio_30d,json=amountToAvgRatio30d,proto3" json:"amount_to_avg_ratio_30d,omitempty"`
	BalanceVolatilityZScore float64                `protobuf:"fixed64,5,opt,name=balance_volatility_z_score,json=balanceVolatilityZScore,proto3" json:"balance_volatility_z_score,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *FeatureSample) Reset() {
	*x = FeatureSample{}
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureSample) ProtoMessage() {}

func (x *FeatureSample) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureSample.ProtoReflect.Descriptor instead.
func (*FeatureSample) Descriptor() ([]byte, []int) {
	return file_proto_crud_v1_analytics_proto_rawDescGZIP(), []int{15}
}

func (x *FeatureSample) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *FeatureSample) GetIsFraudulent() bool {
	if x != nil {
		return x.IsFraudulent
	}
	return false
}

func (x *FeatureSample) GetVelocity_24H() float64 {
	if x != nil {
		return x.Velocity_24H
	}
	return 0
}

func (x *FeatureSample) GetAmountToAvgRatio_30D() float64 {
	if x != nil {
		return x.AmountToAvgRatio_30D
	}
	return 0
}

func (x *FeatureSample) GetBalanceVolatilityZScore() float64 {
	if x != nil {
		return x.BalanceVolatilityZScore
	}
	return 0
}

type GetFeatureSampleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Samples       []*FeatureSample       `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeatureSampleResponse) Reset() {
	*x = GetFeatureSampleResponse{}
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeatureSampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeatureSampleResponse) ProtoMessage() {}

func (x *GetFeatureSampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeatureSampleResponse.ProtoReflect.Descriptor instead.
func (*GetFeatureSampleResponse) Descriptor() ([]byte, []int) {
	return file_proto_crud_v1_analytics_proto_rawDescGZIP(), []int{16}
}

func (x *GetFeatureSampleResponse) GetSamples() []*FeatureSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

type GetSchemaSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableNames    []string               `protobuf:"bytes,1,rep,name=table_names,json=tableNames,proto3" json:"table_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaSummaryRequest) Reset() {
	*x = GetSchemaSummaryRequest{}
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaSummaryRequest) ProtoMessage() {}

func (x *GetSchemaSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaSummaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_crud_v1_analytics_proto_rawDescGZIP(), []int{17}
}

func (x *GetSchemaSummaryRequest) GetTableNames() []string {
	if x != nil {
		return x.TableNames
	}
	return nil
}

type ColumnInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TableName       string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	ColumnName      string                 `protobuf:"bytes,2,opt,name=column_name,json=columnName,proto3" json:"column_name,omitempty"`
	DataType        string                 `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	IsNullable      string                 `protobuf:"bytes,4,opt,name=is_nullable,json=isNullable,proto3" json:"is_nullable,omitempty"`
	OrdinalPosition int32                  `protobuf:"varint,5,opt,name=ordinal_position,json=ordinalPosition,proto3" json:"ordinal_position,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ColumnInfo) Reset() {
	*x = ColumnInfo{}
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnInfo) ProtoMessage() {}

func (x *ColumnInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnInfo.ProtoReflect.Descriptor instead.
func (*ColumnInfo) Descriptor() ([]byte, []int) {
	return file_proto_crud_v1_analytics_proto_rawDescGZIP(), []int{18}
}

func (x *ColumnInfo) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *ColumnInfo) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

func (x *ColumnInfo) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *ColumnInfo) GetIsNullable() string {
	if x != nil {
		return x.IsNullable
	}
	return ""
}

func (x *ColumnInfo) GetOrdinalPosition() int32 {
	if x != nil {
		return x.OrdinalPosition
	}
	return 0
}

type GetSchemaSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []*ColumnInfo          `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaSummaryResponse) Reset() {
	*x = GetSchemaSummaryResponse{}
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaSummaryResponse) ProtoMessage() {}

func (x *GetSchemaSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_crud_v1_analytics_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaSummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_crud_v1_analytics_proto_rawDescGZIP(), []int{19}
}

func (x *GetSchemaSummaryResponse) GetColumns() []*ColumnInfo {
	if x != nil {
		return x.Columns
	}
	return nil
}

var File_proto_crud_v1_analytics_proto protoreflect.FileDescriptor

const file_proto_crud_v1_analytics_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/crud/v1/analytics.proto\x12\acrud.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"*\n" +
	"\x14GetDailyStatsRequest\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x05R\x04days\"\xd1\x01\n" +
	"\tDailyStat\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12-\n" +
	"\x12total_transactions\x18\x02 \x01(\x03R\x11totalTransactions\x12\x1f\n" +
	"\vfraud_count\x18\x03 \x01(\x03R\n" +
	"fraudCount\x12\x1d\n" +
	"\n" +
	"fraud_rate\x18\x04 \x01(\x01R\tfraudRate\x12!\n" +
	"\ftotal_amount\x18\x05 \x01(\x01R\vtotalAmount\x12\x1e\n" +
	"\vavg_z_score\x18\x06 \x01(\x01R\tavgZScore\"A\n" +
	"\x15GetDailyStatsResponse\x12(\n" +
	"\x05stats\x18\x01 \x03(\v2\x12.crud.v1.DailyStatR\x05stats\"H\n" +
	"\x1cGetTransactionDetailsRequest\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x05R\x04days\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x9d\x04\n" +
	"\x11TransactionDetail\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12*\n" +
	"\x11is_train_eligible\x18\x04 \x01(\bR\x0fisTrainEligible\x12 \n" +
	"\fis_pre_fraud\x18\x05 \x01(\bR\n" +
	"isPreFraud\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x01R\x06amount\x12#\n" +
	"\ris_fraudulent\x18\a \x01(\bR\fisFraudulent\x12\x1d\n" +
	"\n" +
	"fraud_type\x18\b \x01(\tR\tfraudType\x12'\n" +
	"\x10is_off_hours_txn\x18\t \x01(\bR\risOffHoursTxn\x12.\n" +
	"\x13merchant_risk_score\x18\n" +
	" \x01(\x05R\x11merchantRiskScore\x12!\n" +
	"\fvelocity_24h\x18\v \x01(\x05R\vvelocity24h\x124\n" +
	"\x17amount_to_avg_ratio_30d\x18\f \x01(\x01R\x13amountToAvgRatio30d\x12;\n" +
	"\x1abalance_volatility_z_score\x18\r \x01(\x01R\x17balanceVolatilityZScore\"_\n" +
	"\x1dGetTransactionDetailsResponse\x12>\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1a.crud.v1.TransactionDetailR\ftransactions\".\n" +
	"\x16GetRecentAlertsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\xca\x03\n" +
	"\x05Alert\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12#\n" +
	"\ris_fraudulent\x18\x05 \x01(\bR\fisFraudulent\x12\x1d\n" +
	"\n" +
	"fraud_type\x18\x06 \x01(\tR\tfraudType\x12.\n" +
	"\x13merchant_risk_score\x18\a \x01(\x05R\x11merchantRiskScore\x12!\n" +
	"\fvelocity_24h\x18\b \x01(\x05R\vvelocity24h\x124\n" +
	"\x17amount_to_avg_ratio_30d\x18\t \x01(\x01R\x13amountToAvgRatio30d\x12;\n" +
	"\x1abalance_volatility_z_score\x18\n" +
	" \x01(\x01R\x17balanceVolatilityZScore\x12.\n" +
	"\x13computed_risk_score\x18\v \x01(\x05R\x11computedRiskScore\"A\n" +
	"\x17GetRecentAlertsResponse\x12&\n" +
	"\x06alerts\x18\x01 \x03(\v2\x0e.crud.v1.AlertR\x06alerts\"\x1b\n" +
	"\x19GetOverviewMetricsRequest\"\xa2\x04\n" +
	"\x1aGetOverviewMetricsResponse\x12#\n" +
	"\rtotal_records\x18\x01 \x01(\x03R\ftotalRecords\x12#\n" +
	"\rfraud_records\x18\x02 \x01(\x03R\ffraudRecords\x12\x1d\n" +
	"\n" +
	"fraud_rate\x18\x03 \x01(\x01R\tfraudRate\x12!\n" +
	"\funique_users\x18\x04 \x01(\x03R\vuniqueUsers\x12V\n" +
	"\x19min_transaction_timestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x17minTransactionTimestamp\x12V\n" +
	"\x19max_transaction_timestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x17maxTransactionTimestamp\x12@\n" +
	"\x0emin_created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fminCreatedAt\x12@\n" +
	"\x0emax_created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\fmaxCreatedAt\x12!\n" +
	"\ftotal_amount\x18\t \x01(\x01R\vtotalAmount\x12!\n" +
	"\ffraud_amount\x18\n" +
	" \x01(\x01R\vfraudAmount\"\x1e\n" +
	"\x1cGetDatasetFingerprintRequest\"\xc2\x01\n" +
	"\x10TableFingerprint\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12@\n" +
	"\x0emax_created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fmaxCreatedAt\x12?\n" +
	"\rmax_timestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fmaxTimestamp\x12\x15\n" +
	"\x06max_id\x18\x04 \x01(\x03R\x05maxId\"\xaf\x01\n" +
	"\x1dGetDatasetFingerprintResponse\x12F\n" +
	"\x11generated_records\x18\x01 \x01(\v2\x19.crud.v1.TableFingerprintR\x10generatedRecords\x12F\n" +
	"\x11feature_snapshots\x18\x02 \x01(\v2\x19.crud.v1.TableFingerprintR\x10featureSnapshots\"V\n" +
	"\x17GetFeatureSampleRequest\x12\x1f\n" +
	"\vsample_size\x18\x01 \x01(\x05R\n" +
	"sampleSize\x12\x1a\n" +
	"\bstratify\x18\x02 \x01(\bR\bstratify\"\xe7\x01\n" +
	"\rFeatureSample\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12#\n" +
	"\ris_fraudulent\x18\x02 \x01(\bR\fisFraudulent\x12!\n" +
	"\fvelocity_24h\x18\x03 \x01(\x01R\vvelocity24h\x124\n" +
	"\x17amount_to_avg_ratio_30d\x18\x04 \x01(\x01R\x13amountToAvgRatio30d\x12;\n" +
	"\x1abalance_volatility_z_score\x18\x05 \x01(\x01R\x17balanceVolatilityZScore\"L\n" +
	"\x18GetFeatureSampleResponse\x120\n" +
	"\asamples\x18\x01 \x03(\v2\x16.crud.v1.FeatureSampleR\asamples\":\n" +
	"\x17GetSchemaSummaryRequest\x12\x1f\n" +
	"\vtable_names\x18\x01 \x03(\tR\n" +
	"tableNames\"\xb5\x01\n" +
	"\n" +
	"ColumnInfo\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x1f\n" +
	"\vcolumn_name\x18\x02 \x01(\tR\n" +
	"columnName\x12\x1b\n" +
	"\tdata_type\x18\x03 \x01(\tR\bdataType\x12\x1f\n" +
	"\vis_nullable\x18\x04 \x01(\tR\n" +
	"isNullable\x12)\n" +
	"\x10ordinal_position\x18\x05 \x01(\x05R\x0fordinalPosition\"I\n" +
	"\x18GetSchemaSummaryResponse\x12-\n" +
	"\acolumns\x18\x01 \x03(\v2\x13.crud.v1.ColumnInfoR\acolumns2\x99\x05\n" +
	"\x10AnalyticsService\x12N\n" +
	"\rGetDailyStats\x12\x1d.crud.v1.GetDailyStatsRequest\x1a\x1e.crud.v1.GetDailyStatsResponse\x12f\n" +
	"\x15GetTransactionDetails\x12%.crud.v1.GetTransactionDetailsRequest\x1a&.crud.v1.GetTransactionDetailsResponse\x12T\n" +
	"\x0fGetRecentAlerts\x12\x1f.crud.v1.GetRecentAlertsRequest\x1a .crud.v1.GetRecentAlertsResponse\x12]\n" +
	"\x12GetOverviewMetrics\x12\".crud.v1.GetOverviewMetricsRequest\x1a#.crud.v1.GetOverviewMetricsResponse\x12f\n" +
	"\x15GetDatasetFingerprint\x12%.crud.v1.GetDatasetFingerprintRequest\x1a&.crud.v1.GetDatasetFingerprintResponse\x12W\n" +
	"\x10GetFeatureSample\x12 .crud.v1.GetFeatureSampleRequest\x1a!.crud.v1.GetFeatureSampleResponse\x12W\n" +
	"\x10GetSchemaSummary\x12 .crud.v1.GetSchemaSummaryRequest\x1a!.crud.v1.GetSchemaSummaryResponseBSZQgithub.com/jonkmatsumo/label-lag/src/services/analytics-crud/proto/crud/v1;crudv1b\x06proto3"

var (
	file_proto_crud_v1_analytics_proto_rawDescOnce sync.Once
	file_proto_crud_v1_analytics_proto_rawDescData []byte
)

func file_proto_crud_v1_analytics_proto_rawDescGZIP() []byte {
	file_proto_crud_v1_analytics_proto_rawDescOnce.Do(func() {
		file_proto_crud_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_crud_v1_analytics_proto_rawDesc), len(file_proto_crud_v1_analytics_proto_rawDesc)))
	})
	return file_proto_crud_v1_analytics_proto_rawDescData
}

var file_proto_crud_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_crud_v1_analytics_proto_goTypes = []any{
	(*GetDailyStatsRequest)(nil),          // 0: crud.v1.GetDailyStatsRequest
	(*DailyStat)(nil),                     // 1: crud.v1.DailyStat
	(*GetDailyStatsResponse)(nil),         // 2: crud.v1.GetDailyStatsResponse
	(*GetTransactionDetailsRequest)(nil),  // 3: crud.v1.GetTransactionDetailsRequest
	(*TransactionDetail)(nil),             // 4: crud.v1.TransactionDetail
	(*GetTransactionDetailsResponse)(nil), // 5: crud.v1.GetTransactionDetailsResponse
	(*GetRecentAlertsRequest)(nil),        // 6: crud.v1.GetRecentAlertsRequest
	(*Alert)(nil),                         // 7: crud.v1.Alert
	(*GetRecentAlertsResponse)(nil),       // 8: crud.v1.GetRecentAlertsResponse
	(*GetOverviewMetricsRequest)(nil),     // 9: crud.v1.GetOverviewMetricsRequest
	(*GetOverviewMetricsResponse)(nil),    // 10: crud.v1.GetOverviewMetricsResponse
	(*GetDatasetFingerprintRequest)(nil),  // 11: crud.v1.GetDatasetFingerprintRequest
	(*TableFingerprint)(nil),              // 12: crud.v1.TableFingerprint
	(*GetDatasetFingerprintResponse)(nil), // 13: crud.v1.GetDatasetFingerprintResponse
	(*GetFeatureSampleRequest)(nil),       // 14: crud.v1.GetFeatureSampleRequest
	(*FeatureSample)(nil),                 // 15: crud.v1.FeatureSample
	(*GetFeatureSampleResponse)(nil),      // 16: crud.v1.GetFeatureSampleResponse
	(*GetSchemaSummaryRequest)(nil),       // 17: crud.v1.GetSchemaSummaryRequest
	(*ColumnInfo)(nil),                    // 18: crud.v1.ColumnInfo
	(*GetSchemaSummaryResponse)(nil),      // 19: crud.v1.GetSchemaSummaryResponse
	(*timestamppb.Timestamp)(nil),         // 20: google.protobuf.Timestamp
}
var file_proto_crud_v1_analytics_proto_depIdxs = []int32{
	1,  // 0: crud.v1.GetDailyStatsResponse.stats:type_name -> crud.v1.DailyStat
	20, // 1: crud.v1.TransactionDetail.created_at:type_name -> google.protobuf.Timestamp
	4,  // 2: crud.v1.GetTransactionDetailsResponse.transactions:type_name -> crud.v1.TransactionDetail
	20, // 3: crud.v1.Alert.created_at:type_name -> google.protobuf.Timestamp
	7,  // 4: crud.v1.GetRecentAlertsResponse.alerts:type_name -> crud.v1.Alert
	20, // 5: crud.v1.GetOverviewMetricsResponse.min_transaction_timestamp:type_name -> google.protobuf.Timestamp
	20, // 6: crud.v1.GetOverviewMetricsResponse.max_transaction_timestamp:type_name -> google.protobuf.Timestamp
	20, // 7: crud.v1.GetOverviewMetricsResponse.min_created_at:type_name -> google.protobuf.Timestamp
	20, // 8: crud.v1.GetOverviewMetricsResponse.max_created_at:type_name -> google.protobuf.Timestamp
	20, // 9: crud.v1.TableFingerprint.max_created_at:type_name -> google.protobuf.Timestamp
	20, // 10: crud.v1.TableFingerprint.max_timestamp:type_name -> google.protobuf.Timestamp
	12, // 11: crud.v1.GetDatasetFingerprintResponse.generated_records:type_name -> crud.v1.TableFingerprint
	12, // 12: crud.v1.GetDatasetFingerprintResponse.feature_snapshots:type_name -> crud.v1.TableFingerprint
	15, // 13: crud.v1.GetFeatureSampleResponse.samples:type_name -> crud.v1.FeatureSample
	18, // 14: crud.v1.GetSchemaSummaryResponse.columns:type_name -> crud.v1.ColumnInfo
	0,  // 15: crud.v1.AnalyticsService.GetDailyStats:input_type -> crud.v1.GetDailyStatsRequest
	3,  // 16: crud.v1.AnalyticsService.GetTransactionDetails:input_type -> crud.v1.GetTransactionDetailsRequest
	6,  // 17: crud.v1.AnalyticsService.GetRecentAlerts:input_type -> crud.v1.GetRecentAlertsRequest
	9,  // 18: crud.v1.AnalyticsService.GetOverviewMetrics:input_type -> crud.v1.GetOverviewMetricsRequest
	11, // 19: crud.v1.AnalyticsService.GetDatasetFingerprint:input_type -> crud.v1.GetDatasetFingerprintRequest
	14, // 20: crud.v1.AnalyticsService.GetFeatureSample:input_type -> crud.v1.GetFeatureSampleRequest
	17, // 21: crud.v1.AnalyticsService.GetSchemaSummary:input_type -> crud.v1.GetSchemaSummaryRequest
	2,  // 22: crud.v1.AnalyticsService.GetDailyStats:output_type -> crud.v1.GetDailyStatsResponse
	5,  // 23: crud.v1.AnalyticsService.GetTransactionDetails:output_type -> crud.v1.GetTransactionDetailsResponse
	8,  // 24: crud.v1.AnalyticsService.GetRecentAlerts:output_type -> crud.v1.GetRecentAlertsResponse
	10, // 25: crud.v1.AnalyticsService.GetOverviewMetrics:output_type -> crud.v1.GetOverviewMetricsResponse
	13, // 26: crud.v1.AnalyticsService.GetDatasetFingerprint:output_type -> crud.v1.GetDatasetFingerprintResponse
	16, // 27: crud.v1.AnalyticsService.GetFeatureSample:output_type -> crud.v1.GetFeatureSampleResponse
	19, // 28: crud.v1.AnalyticsService.GetSchemaSummary:output_type -> crud.v1.GetSchemaSummaryResponse
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_crud_v1_analytics_proto_init() }
func file_proto_crud_v1_analytics_proto_init() {
	if File_proto_crud_v1_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_crud_v1_analytics_proto_rawDesc), len(file_proto_crud_v1_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_crud_v1_analytics_proto_goTypes,
		DependencyIndexes: file_proto_crud_v1_analytics_proto_depIdxs,
		MessageInfos:      file_proto_crud_v1_analytics_proto_msgTypes,
	}.Build()
	File_proto_crud_v1_analytics_proto = out.File
	file_proto_crud_v1_analytics_proto_goTypes = nil
	file_proto_crud_v1_analytics_proto_depIdxs = nil
}
