// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/crud/v1/analytics.proto

package crudv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_GetDailyStats_FullMethodName         = "/crud.v1.AnalyticsService/GetDailyStats"
	AnalyticsService_GetTransactionDetails_FullMethodName = "/crud.v1.AnalyticsService/GetTransactionDetails"
	AnalyticsService_GetRecentAlerts_FullMethodName       = "/crud.v1.AnalyticsService/GetRecentAlerts"
	AnalyticsService_GetOverviewMetrics_FullMethodName    = "/crud.v1.AnalyticsService/GetOverviewMetrics"
	AnalyticsService_GetDatasetFingerprint_FullMethodName = "/crud.v1.AnalyticsService/GetDatasetFingerprint"
	AnalyticsService_GetFeatureSample_FullMethodName      = "/crud.v1.AnalyticsService/GetFeatureSample"
	AnalyticsService_GetSchemaSummary_FullMethodName      = "/crud.v1.AnalyticsService/GetSchemaSummary"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	GetDailyStats(ctx context.Context, in *GetDailyStatsRequest, opts ...grpc.CallOption) (*GetDailyStatsResponse, error)
	GetTransactionDetails(ctx context.Context, in *GetTransactionDetailsRequest, opts ...grpc.CallOption) (*GetTransactionDetailsResponse, error)
	GetRecentAlerts(ctx context.Context, in *GetRecentAlertsRequest, opts ...grpc.CallOption) (*GetRecentAlertsResponse, error)
	GetOverviewMetrics(ctx context.Context, in *GetOverviewMetricsRequest, opts ...grpc.CallOption) (*GetOverviewMetricsResponse, error)
	GetDatasetFingerprint(ctx context.Context, in *GetDatasetFingerprintRequest, opts ...grpc.CallOption) (*GetDatasetFingerprintResponse, error)
	GetFeatureSample(ctx context.Context, in *GetFeatureSampleRequest, opts ...grpc.CallOption) (*GetFeatureSampleResponse, error)
	GetSchemaSummary(ctx context.Context, in *GetSchemaSummaryRequest, opts ...grpc.CallOption) (*GetSchemaSummaryResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetDailyStats(ctx context.Context, in *GetDailyStatsRequest, opts ...grpc.CallOption) (*GetDailyStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDailyStatsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetDailyStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetTransactionDetails(ctx context.Context, in *GetTransactionDetailsRequest, opts ...grpc.CallOption) (*GetTransactionDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionDetailsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetTransactionDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetRecentAlerts(ctx context.Context, in *GetRecentAlertsRequest, opts ...grpc.CallOption) (*GetRecentAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecentAlertsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetRecentAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetOverviewMetrics(ctx context.Context, in *GetOverviewMetricsRequest, opts ...grpc.CallOption) (*GetOverviewMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOverviewMetricsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetOverviewMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetDatasetFingerprint(ctx context.Context, in *GetDatasetFingerprintRequest, opts ...grpc.CallOption) (*GetDatasetFingerprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDatasetFingerprintResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetDatasetFingerprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetFeatureSample(ctx context.Context, in *GetFeatureSampleRequest, opts ...grpc.CallOption) (*GetFeatureSampleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFeatureSampleResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetFeatureSample_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetSchemaSummary(ctx context.Context, in *GetSchemaSummaryRequest, opts ...grpc.CallOption) (*GetSchemaSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSchemaSummaryResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetSchemaSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
type AnalyticsServiceServer interface {
	GetDailyStats(context.Context, *GetDailyStatsRequest) (*GetDailyStatsResponse, error)
	GetTransactionDetails(context.Context, *GetTransactionDetailsRequest) (*GetTransactionDetailsResponse, error)
	GetRecentAlerts(context.Context, *GetRecentAlertsRequest) (*GetRecentAlertsResponse, error)
	GetOverviewMetrics(context.Context, *GetOverviewMetricsRequest) (*GetOverviewMetricsResponse, error)
	GetDatasetFingerprint(context.Context, *GetDatasetFingerprintRequest) (*GetDatasetFingerprintResponse, error)
	GetFeatureSample(context.Context, *GetFeatureSampleRequest) (*GetFeatureSampleResponse, error)
	GetSchemaSummary(context.Context, *GetSchemaSummaryRequest) (*GetSchemaSummaryResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetDailyStats(context.Context, *GetDailyStatsRequest) (*GetDailyStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDailyStats not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetTransactionDetails(context.Context, *GetTransactionDetailsRequest) (*GetTransactionDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransactionDetails not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetRecentAlerts(context.Context, *GetRecentAlertsRequest) (*GetRecentAlertsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecentAlerts not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetOverviewMetrics(context.Context, *GetOverviewMetricsRequest) (*GetOverviewMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOverviewMetrics not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetDatasetFingerprint(context.Context, *GetDatasetFingerprintRequest) (*GetDatasetFingerprintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDatasetFingerprint not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetFeatureSample(context.Context, *GetFeatureSampleRequest) (*GetFeatureSampleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeatureSample not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetSchemaSummary(context.Context, *GetSchemaSummaryRequest) (*GetSchemaSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchemaSummary not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetDailyStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetDailyStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetDailyStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetDailyStats(ctx, req.(*GetDailyStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetTransactionDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetTransactionDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetTransactionDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetTransactionDetails(ctx, req.(*GetTransactionDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetRecentAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetRecentAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetRecentAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetRecentAlerts(ctx, req.(*GetRecentAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetOverviewMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOverviewMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetOverviewMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetOverviewMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetOverviewMetrics(ctx, req.(*GetOverviewMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetDatasetFingerprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatasetFingerprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetDatasetFingerprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetDatasetFingerprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetDatasetFingerprint(ctx, req.(*GetDatasetFingerprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetFeatureSample_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeatureSampleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetFeatureSample(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetFeatureSample_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetFeatureSample(ctx, req.(*GetFeatureSampleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetSchemaSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetSchemaSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetSchemaSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetSchemaSummary(ctx, req.(*GetSchemaSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crud.v1.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDailyStats",
			Handler:    _AnalyticsService_GetDailyStats_Handler,
		},
		{
			MethodName: "GetTransactionDetails",
			Handler:    _AnalyticsService_GetTransactionDetails_Handler,
		},
		{
			MethodName: "GetRecentAlerts",
			Handler:    _AnalyticsService_GetRecentAlerts_Handler,
		},
		{
			MethodName: "GetOverviewMetrics",
			Handler:    _AnalyticsService_GetOverviewMetrics_Handler,
		},
		{
			MethodName: "GetDatasetFingerprint",
			Handler:    _AnalyticsService_GetDatasetFingerprint_Handler,
		},
		{
			MethodName: "GetFeatureSample",
			Handler:    _AnalyticsService_GetFeatureSample_Handler,
		},
		{
			MethodName: "GetSchemaSummary",
			Handler:    _AnalyticsService_GetSchemaSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/crud/v1/analytics.proto",
}
