# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference/v1/signal.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference/v1/signal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19inference/v1/signal.proto\x12\ngateway.v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1cgoogle/protobuf/struct.proto\"a\n\rSignalRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x1d\n\x15\x63lient_transaction_id\x18\x04 \x01(\t\"+\n\rRiskComponent\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\"U\n\x0bMatchedRule\x12\x0f\n\x07rule_id\x18\x01 \x01(\t\x12\x10\n\x08severity\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\x13\n\x0b\x65xplanation\x18\x04 \x01(\t\"\xa1\x03\n\x0eSignalResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x05\x12\x12\n\nrisk_label\x18\t \x01(\t\x12\x12\n\nlatency_ms\x18\n \x01(\x01\x12\x32\n\x0frisk_components\x18\x03 \x03(\x0b\x32\x19.gateway.v1.RiskComponent\x12\x15\n\rmodel_version\x18\x04 \x01(\t\x12.\n\rmatched_rules\x18\x05 \x03(\x0b\x32\x17.gateway.v1.MatchedRule\x12\x30\n\x0bmodel_score\x18\x06 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12\x33\n\rrules_version\x18\x07 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x35\n\x14shadow_matched_rules\x18\x08 \x03(\x0b\x32\x17.gateway.v1.MatchedRule\x12+\n\ndebug_info\x18\x0b \x01(\x0b\x32\x17.google.protobuf.StructBQZOgithub.com/jonkmatsumo/label-lag/go/inference/internal/http/gatewayv1;gatewayv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.v1.signal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZOgithub.com/jonkmatsumo/label-lag/go/inference/internal/http/gatewayv1;gatewayv1'
  _globals['_SIGNALREQUEST']._serialized_start=103
  _globals['_SIGNALREQUEST']._serialized_end=200
  _globals['_RISKCOMPONENT']._serialized_start=202
  _globals['_RISKCOMPONENT']._serialized_end=245
  _globals['_MATCHEDRULE']._serialized_start=247
  _globals['_MATCHEDRULE']._serialized_end=332
  _globals['_SIGNALRESPONSE']._serialized_start=335
  _globals['_SIGNALRESPONSE']._serialized_end=752
# @@protoc_insertion_point(module_scope)
