// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: gateway/v1/signal.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount              float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency            string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	ClientTransactionId string                 `protobuf:"bytes,4,opt,name=client_transaction_id,json=clientTransactionId,proto3" json:"client_transaction_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	mi := &file_gateway_v1_signal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_signal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_signal_proto_rawDescGZIP(), []int{0}
}

func (x *SignalRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SignalRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SignalRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SignalRequest) GetClientTransactionId() string {
	if x != nil {
		return x.ClientTransactionId
	}
	return ""
}

type RiskComponent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskComponent) Reset() {
	*x = RiskComponent{}
	mi := &file_gateway_v1_signal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskComponent) ProtoMessage() {}

func (x *RiskComponent) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_signal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskComponent.ProtoReflect.Descriptor instead.
func (*RiskComponent) Descriptor() ([]byte, []int) {
	return file_gateway_v1_signal_proto_rawDescGZIP(), []int{1}
}

func (x *RiskComponent) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RiskComponent) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type MatchedRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchedRule) Reset() {
	*x = MatchedRule{}
	mi := &file_gateway_v1_signal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchedRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchedRule) ProtoMessage() {}

func (x *MatchedRule) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_signal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchedRule.ProtoReflect.Descriptor instead.
func (*MatchedRule) Descriptor() ([]byte, []int) {
	return file_gateway_v1_signal_proto_rawDescGZIP(), []int{2}
}

func (x *MatchedRule) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *MatchedRule) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *MatchedRule) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SignalResponse struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	RequestId          string                  `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Score              int32                   `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	RiskComponents     []*RiskComponent        `protobuf:"bytes,3,rep,name=risk_components,json=riskComponents,proto3" json:"risk_components,omitempty"`
	ModelVersion       string                  `protobuf:"bytes,4,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	MatchedRules       []*MatchedRule          `protobuf:"bytes,5,rep,name=matched_rules,json=matchedRules,proto3" json:"matched_rules,omitempty"`
	ModelScore         *wrapperspb.Int32Value  `protobuf:"bytes,6,opt,name=model_score,json=modelScore,proto3" json:"model_score,omitempty"`
	RulesVersion       *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=rules_version,json=rulesVersion,proto3" json:"rules_version,omitempty"`
	ShadowMatchedRules []*MatchedRule          `protobuf:"bytes,8,rep,name=shadow_matched_rules,json=shadowMatchedRules,proto3" json:"shadow_matched_rules,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_gateway_v1_signal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_signal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_signal_proto_rawDescGZIP(), []int{3}
}

func (x *SignalResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SignalResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SignalResponse) GetRiskComponents() []*RiskComponent {
	if x != nil {
		return x.RiskComponents
	}
	return nil
}

func (x *SignalResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *SignalResponse) GetMatchedRules() []*MatchedRule {
	if x != nil {
		return x.MatchedRules
	}
	return nil
}

func (x *SignalResponse) GetModelScore() *wrapperspb.Int32Value {
	if x != nil {
		return x.ModelScore
	}
	return nil
}

func (x *SignalResponse) GetRulesVersion() *wrapperspb.StringValue {
	if x != nil {
		return x.RulesVersion
	}
	return nil
}

func (x *SignalResponse) GetShadowMatchedRules() []*MatchedRule {
	if x != nil {
		return x.ShadowMatchedRules
	}
	return nil
}

var File_gateway_v1_signal_proto protoreflect.FileDescriptor

const file_gateway_v1_signal_proto_rawDesc = "" +
	"\n" +
	"\x17gateway/v1/signal.proto\x12\n" +
	"gateway.v1\x1a\x1egoogle/protobuf/wrappers.proto\"\x90\x01\n" +
	"\rSignalRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x122\n" +
	"\x15client_transaction_id\x18\x04 \x01(\tR\x13clientTransactionId\"7\n" +
	"\rRiskComponent\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"Z\n" +
	"\vMatchedRule\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xb8\x03\n" +
	"\x0eSignalResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12B\n" +
	"\x0frisk_components\x18\x03 \x03(\v2\x19.gateway.v1.RiskComponentR\x0eriskComponents\x12#\n" +
	"\rmodel_version\x18\x04 \x01(\tR\fmodelVersion\x12<\n" +
	"\rmatched_rules\x18\x05 \x03(\v2\x17.gateway.v1.MatchedRuleR\fmatchedRules\x12<\n" +
	"\vmodel_score\x18\x06 \x01(\v2\x1b.google.protobuf.Int32ValueR\n" +
	"modelScore\x12A\n" +
	"\rrules_version\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\frulesVersion\x12I\n" +
	"\x14shadow_matched_rules\x18\b \x03(\v2\x17.gateway.v1.MatchedRuleR\x12shadowMatchedRulesBcZagithub.com/jonkmatsumo/label-lag/src/services/inference-gateway/internal/http/gatewayv1;gatewayv1b\x06proto3"

var (
	file_gateway_v1_signal_proto_rawDescOnce sync.Once
	file_gateway_v1_signal_proto_rawDescData []byte
)

func file_gateway_v1_signal_proto_rawDescGZIP() []byte {
	file_gateway_v1_signal_proto_rawDescOnce.Do(func() {
		file_gateway_v1_signal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_signal_proto_rawDesc), len(file_gateway_v1_signal_proto_rawDesc)))
	})
	return file_gateway_v1_signal_proto_rawDescData
}

var file_gateway_v1_signal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gateway_v1_signal_proto_goTypes = []any{
	(*SignalRequest)(nil),          // 0: gateway.v1.SignalRequest
	(*RiskComponent)(nil),          // 1: gateway.v1.RiskComponent
	(*MatchedRule)(nil),            // 2: gateway.v1.MatchedRule
	(*SignalResponse)(nil),         // 3: gateway.v1.SignalResponse
	(*wrapperspb.Int32Value)(nil),  // 4: google.protobuf.Int32Value
	(*wrapperspb.StringValue)(nil), // 5: google.protobuf.StringValue
}
var file_gateway_v1_signal_proto_depIdxs = []int32{
	1, // 0: gateway.v1.SignalResponse.risk_components:type_name -> gateway.v1.RiskComponent
	2, // 1: gateway.v1.SignalResponse.matched_rules:type_name -> gateway.v1.MatchedRule
	4, // 2: gateway.v1.SignalResponse.model_score:type_name -> google.protobuf.Int32Value
	5, // 3: gateway.v1.SignalResponse.rules_version:type_name -> google.protobuf.StringValue
	2, // 4: gateway.v1.SignalResponse.shadow_matched_rules:type_name -> gateway.v1.MatchedRule
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_gateway_v1_signal_proto_init() }
func file_gateway_v1_signal_proto_init() {
	if File_gateway_v1_signal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_signal_proto_rawDesc), len(file_gateway_v1_signal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_v1_signal_proto_goTypes,
		DependencyIndexes: file_gateway_v1_signal_proto_depIdxs,
		MessageInfos:      file_gateway_v1_signal_proto_msgTypes,
	}.Build()
	File_gateway_v1_signal_proto = out.File
	file_gateway_v1_signal_proto_goTypes = nil
	file_gateway_v1_signal_proto_depIdxs = nil
}
