// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: inference/v1/gateway.proto

package gatewayv1

import (
	v1 "github.com/jonkmatsumo/label-lag/go/analytics/proto/crud/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvaluateRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Features      *structpb.Struct       `protobuf:"bytes,1,opt,name=features,proto3" json:"features,omitempty"` // Flexible map for feature hydration
	BaseScore     int32                  `protobuf:"varint,2,opt,name=base_score,json=baseScore,proto3" json:"base_score,omitempty"`
	Ruleset       *RuleSet               `protobuf:"bytes,3,opt,name=ruleset,proto3" json:"ruleset,omitempty"` // Optional, if not provided uses default
	ShadowMode    bool                   `protobuf:"varint,4,opt,name=shadow_mode,json=shadowMode,proto3" json:"shadow_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRulesRequest) Reset() {
	*x = EvaluateRulesRequest{}
	mi := &file_inference_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRulesRequest) ProtoMessage() {}

func (x *EvaluateRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRulesRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRulesRequest) Descriptor() ([]byte, []int) {
	return file_inference_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateRulesRequest) GetFeatures() *structpb.Struct {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *EvaluateRulesRequest) GetBaseScore() int32 {
	if x != nil {
		return x.BaseScore
	}
	return 0
}

func (x *EvaluateRulesRequest) GetRuleset() *RuleSet {
	if x != nil {
		return x.Ruleset
	}
	return nil
}

func (x *EvaluateRulesRequest) GetShadowMode() bool {
	if x != nil {
		return x.ShadowMode
	}
	return false
}

type EvaluateRulesResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FinalScore         int32                  `protobuf:"varint,1,opt,name=final_score,json=finalScore,proto3" json:"final_score,omitempty"`
	BaselineScore      int32                  `protobuf:"varint,2,opt,name=baseline_score,json=baselineScore,proto3" json:"baseline_score,omitempty"`
	ShadowScore        int32                  `protobuf:"varint,3,opt,name=shadow_score,json=shadowScore,proto3" json:"shadow_score,omitempty"` // Only if shadow_mode=true
	MatchedRules       []string               `protobuf:"bytes,4,rep,name=matched_rules,json=matchedRules,proto3" json:"matched_rules,omitempty"`
	Explanations       []*Explanation         `protobuf:"bytes,5,rep,name=explanations,proto3" json:"explanations,omitempty"`
	ShadowMatchedRules []string               `protobuf:"bytes,6,rep,name=shadow_matched_rules,json=shadowMatchedRules,proto3" json:"shadow_matched_rules,omitempty"`
	ShadowExplanations []*Explanation         `protobuf:"bytes,7,rep,name=shadow_explanations,json=shadowExplanations,proto3" json:"shadow_explanations,omitempty"`
	Rejected           bool                   `protobuf:"varint,8,opt,name=rejected,proto3" json:"rejected,omitempty"`
	RulesetVersion     string                 `protobuf:"bytes,9,opt,name=ruleset_version,json=rulesetVersion,proto3" json:"ruleset_version,omitempty"`
	Warnings           []*Conflict            `protobuf:"bytes,10,rep,name=warnings,proto3" json:"warnings,omitempty"`
	EvaluationTimeMs   float64                `protobuf:"fixed64,11,opt,name=evaluation_time_ms,json=evaluationTimeMs,proto3" json:"evaluation_time_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EvaluateRulesResponse) Reset() {
	*x = EvaluateRulesResponse{}
	mi := &file_inference_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRulesResponse) ProtoMessage() {}

func (x *EvaluateRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRulesResponse.ProtoReflect.Descriptor instead.
func (*EvaluateRulesResponse) Descriptor() ([]byte, []int) {
	return file_inference_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluateRulesResponse) GetFinalScore() int32 {
	if x != nil {
		return x.FinalScore
	}
	return 0
}

func (x *EvaluateRulesResponse) GetBaselineScore() int32 {
	if x != nil {
		return x.BaselineScore
	}
	return 0
}

func (x *EvaluateRulesResponse) GetShadowScore() int32 {
	if x != nil {
		return x.ShadowScore
	}
	return 0
}

func (x *EvaluateRulesResponse) GetMatchedRules() []string {
	if x != nil {
		return x.MatchedRules
	}
	return nil
}

func (x *EvaluateRulesResponse) GetExplanations() []*Explanation {
	if x != nil {
		return x.Explanations
	}
	return nil
}

func (x *EvaluateRulesResponse) GetShadowMatchedRules() []string {
	if x != nil {
		return x.ShadowMatchedRules
	}
	return nil
}

func (x *EvaluateRulesResponse) GetShadowExplanations() []*Explanation {
	if x != nil {
		return x.ShadowExplanations
	}
	return nil
}

func (x *EvaluateRulesResponse) GetRejected() bool {
	if x != nil {
		return x.Rejected
	}
	return false
}

func (x *EvaluateRulesResponse) GetRulesetVersion() string {
	if x != nil {
		return x.RulesetVersion
	}
	return ""
}

func (x *EvaluateRulesResponse) GetWarnings() []*Conflict {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *EvaluateRulesResponse) GetEvaluationTimeMs() float64 {
	if x != nil {
		return x.EvaluationTimeMs
	}
	return 0
}

type EvaluateRulesDiffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Features      *structpb.Struct       `protobuf:"bytes,1,opt,name=features,proto3" json:"features,omitempty"`
	BaseScore     int32                  `protobuf:"varint,2,opt,name=base_score,json=baseScore,proto3" json:"base_score,omitempty"`
	RulesetA      *RuleSet               `protobuf:"bytes,3,opt,name=ruleset_a,json=rulesetA,proto3" json:"ruleset_a,omitempty"`
	RulesetB      *RuleSet               `protobuf:"bytes,4,opt,name=ruleset_b,json=rulesetB,proto3" json:"ruleset_b,omitempty"`
	ShadowMode    bool                   `protobuf:"varint,5,opt,name=shadow_mode,json=shadowMode,proto3" json:"shadow_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRulesDiffRequest) Reset() {
	*x = EvaluateRulesDiffRequest{}
	mi := &file_inference_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRulesDiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRulesDiffRequest) ProtoMessage() {}

func (x *EvaluateRulesDiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRulesDiffRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRulesDiffRequest) Descriptor() ([]byte, []int) {
	return file_inference_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *EvaluateRulesDiffRequest) GetFeatures() *structpb.Struct {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *EvaluateRulesDiffRequest) GetBaseScore() int32 {
	if x != nil {
		return x.BaseScore
	}
	return 0
}

func (x *EvaluateRulesDiffRequest) GetRulesetA() *RuleSet {
	if x != nil {
		return x.RulesetA
	}
	return nil
}

func (x *EvaluateRulesDiffRequest) GetRulesetB() *RuleSet {
	if x != nil {
		return x.RulesetB
	}
	return nil
}

func (x *EvaluateRulesDiffRequest) GetShadowMode() bool {
	if x != nil {
		return x.ShadowMode
	}
	return false
}

type EvaluateRulesDiffResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	A                     *EvaluateRulesResponse `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B                     *EvaluateRulesResponse `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	Diff                  *RulesDiffSummary      `protobuf:"bytes,3,opt,name=diff,proto3" json:"diff,omitempty"`
	TotalEvaluationTimeMs float64                `protobuf:"fixed64,4,opt,name=total_evaluation_time_ms,json=totalEvaluationTimeMs,proto3" json:"total_evaluation_time_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *EvaluateRulesDiffResponse) Reset() {
	*x = EvaluateRulesDiffResponse{}
	mi := &file_inference_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRulesDiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRulesDiffResponse) ProtoMessage() {}

func (x *EvaluateRulesDiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRulesDiffResponse.ProtoReflect.Descriptor instead.
func (*EvaluateRulesDiffResponse) Descriptor() ([]byte, []int) {
	return file_inference_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *EvaluateRulesDiffResponse) GetA() *EvaluateRulesResponse {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *EvaluateRulesDiffResponse) GetB() *EvaluateRulesResponse {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *EvaluateRulesDiffResponse) GetDiff() *RulesDiffSummary {
	if x != nil {
		return x.Diff
	}
	return nil
}

func (x *EvaluateRulesDiffResponse) GetTotalEvaluationTimeMs() float64 {
	if x != nil {
		return x.TotalEvaluationTimeMs
	}
	return 0
}

type RulesDiffSummary struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Severity            string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"`
	ScoreDelta          int32                  `protobuf:"varint,2,opt,name=score_delta,json=scoreDelta,proto3" json:"score_delta,omitempty"`
	MatchedRulesAdded   []string               `protobuf:"bytes,3,rep,name=matched_rules_added,json=matchedRulesAdded,proto3" json:"matched_rules_added,omitempty"`
	MatchedRulesRemoved []string               `protobuf:"bytes,4,rep,name=matched_rules_removed,json=matchedRulesRemoved,proto3" json:"matched_rules_removed,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RulesDiffSummary) Reset() {
	*x = RulesDiffSummary{}
	mi := &file_inference_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RulesDiffSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RulesDiffSummary) ProtoMessage() {}

func (x *RulesDiffSummary) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RulesDiffSummary.ProtoReflect.Descriptor instead.
func (*RulesDiffSummary) Descriptor() ([]byte, []int) {
	return file_inference_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *RulesDiffSummary) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *RulesDiffSummary) GetScoreDelta() int32 {
	if x != nil {
		return x.ScoreDelta
	}
	return 0
}

func (x *RulesDiffSummary) GetMatchedRulesAdded() []string {
	if x != nil {
		return x.MatchedRulesAdded
	}
	return nil
}

func (x *RulesDiffSummary) GetMatchedRulesRemoved() []string {
	if x != nil {
		return x.MatchedRulesRemoved
	}
	return nil
}

type RuleSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*v1.Rule             `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleSet) Reset() {
	*x = RuleSet{}
	mi := &file_inference_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleSet) ProtoMessage() {}

func (x *RuleSet) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleSet.ProtoReflect.Descriptor instead.
func (*RuleSet) Descriptor() ([]byte, []int) {
	return file_inference_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *RuleSet) GetRules() []*v1.Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type Explanation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Score         int32                  `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	Explanation   string                 `protobuf:"bytes,6,opt,name=explanation,proto3" json:"explanation,omitempty"`
	ScoreDelta    int32                  `protobuf:"varint,7,opt,name=score_delta,json=scoreDelta,proto3" json:"score_delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Explanation) Reset() {
	*x = Explanation{}
	mi := &file_inference_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Explanation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Explanation) ProtoMessage() {}

func (x *Explanation) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Explanation.ProtoReflect.Descriptor instead.
func (*Explanation) Descriptor() ([]byte, []int) {
	return file_inference_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *Explanation) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *Explanation) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Explanation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Explanation) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Explanation) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Explanation) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *Explanation) GetScoreDelta() int32 {
	if x != nil {
		return x.ScoreDelta
	}
	return 0
}

type Conflict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conflict) Reset() {
	*x = Conflict{}
	mi := &file_inference_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conflict) ProtoMessage() {}

func (x *Conflict) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conflict.ProtoReflect.Descriptor instead.
func (*Conflict) Descriptor() ([]byte, []int) {
	return file_inference_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *Conflict) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_inference_v1_gateway_proto protoreflect.FileDescriptor

const file_inference_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1ainference/v1/gateway.proto\x12\n" +
	"gateway.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1canalytics/v1/analytics.proto\"\xba\x01\n" +
	"\x14EvaluateRulesRequest\x123\n" +
	"\bfeatures\x18\x01 \x01(\v2\x17.google.protobuf.StructR\bfeatures\x12\x1d\n" +
	"\n" +
	"base_score\x18\x02 \x01(\x05R\tbaseScore\x12-\n" +
	"\aruleset\x18\x03 \x01(\v2\x13.gateway.v1.RuleSetR\aruleset\x12\x1f\n" +
	"\vshadow_mode\x18\x04 \x01(\bR\n" +
	"shadowMode\"\x85\x04\n" +
	"\x15EvaluateRulesResponse\x12\x1f\n" +
	"\vfinal_score\x18\x01 \x01(\x05R\n" +
	"finalScore\x12%\n" +
	"\x0ebaseline_score\x18\x02 \x01(\x05R\rbaselineScore\x12!\n" +
	"\fshadow_score\x18\x03 \x01(\x05R\vshadowScore\x12#\n" +
	"\rmatched_rules\x18\x04 \x03(\tR\fmatchedRules\x12;\n" +
	"\fexplanations\x18\x05 \x03(\v2\x17.gateway.v1.ExplanationR\fexplanations\x120\n" +
	"\x14shadow_matched_rules\x18\x06 \x03(\tR\x12shadowMatchedRules\x12H\n" +
	"\x13shadow_explanations\x18\a \x03(\v2\x17.gateway.v1.ExplanationR\x12shadowExplanations\x12\x1a\n" +
	"\brejected\x18\b \x01(\bR\brejected\x12'\n" +
	"\x0fruleset_version\x18\t \x01(\tR\x0erulesetVersion\x120\n" +
	"\bwarnings\x18\n" +
	" \x03(\v2\x14.gateway.v1.ConflictR\bwarnings\x12,\n" +
	"\x12evaluation_time_ms\x18\v \x01(\x01R\x10evaluationTimeMs\"\xf3\x01\n" +
	"\x18EvaluateRulesDiffRequest\x123\n" +
	"\bfeatures\x18\x01 \x01(\v2\x17.google.protobuf.StructR\bfeatures\x12\x1d\n" +
	"\n" +
	"base_score\x18\x02 \x01(\x05R\tbaseScore\x120\n" +
	"\truleset_a\x18\x03 \x01(\v2\x13.gateway.v1.RuleSetR\brulesetA\x120\n" +
	"\truleset_b\x18\x04 \x01(\v2\x13.gateway.v1.RuleSetR\brulesetB\x12\x1f\n" +
	"\vshadow_mode\x18\x05 \x01(\bR\n" +
	"shadowMode\"\xe8\x01\n" +
	"\x19EvaluateRulesDiffResponse\x12/\n" +
	"\x01a\x18\x01 \x01(\v2!.gateway.v1.EvaluateRulesResponseR\x01a\x12/\n" +
	"\x01b\x18\x02 \x01(\v2!.gateway.v1.EvaluateRulesResponseR\x01b\x120\n" +
	"\x04diff\x18\x03 \x01(\v2\x1c.gateway.v1.RulesDiffSummaryR\x04diff\x127\n" +
	"\x18total_evaluation_time_ms\x18\x04 \x01(\x01R\x15totalEvaluationTimeMs\"\xb3\x01\n" +
	"\x10RulesDiffSummary\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x1f\n" +
	"\vscore_delta\x18\x02 \x01(\x05R\n" +
	"scoreDelta\x12.\n" +
	"\x13matched_rules_added\x18\x03 \x03(\tR\x11matchedRulesAdded\x122\n" +
	"\x15matched_rules_removed\x18\x04 \x03(\tR\x13matchedRulesRemoved\".\n" +
	"\aRuleSet\x12#\n" +
	"\x05rules\x18\x01 \x03(\v2\r.crud.v1.RuleR\x05rules\"\xcb\x01\n" +
	"\vExplanation\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x05R\x05score\x12 \n" +
	"\vexplanation\x18\x06 \x01(\tR\vexplanation\x12\x1f\n" +
	"\vscore_delta\x18\a \x01(\x05R\n" +
	"scoreDelta\"$\n" +
	"\bConflict\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xc8\x01\n" +
	"\x0eGatewayService\x12T\n" +
	"\rEvaluateRules\x12 .gateway.v1.EvaluateRulesRequest\x1a!.gateway.v1.EvaluateRulesResponse\x12`\n" +
	"\x11EvaluateRulesDiff\x12$.gateway.v1.EvaluateRulesDiffRequest\x1a%.gateway.v1.EvaluateRulesDiffResponseBQZOgithub.com/jonkmatsumo/label-lag/go/inference/internal/http/gatewayv1;gatewayv1b\x06proto3"

var (
	file_inference_v1_gateway_proto_rawDescOnce sync.Once
	file_inference_v1_gateway_proto_rawDescData []byte
)

func file_inference_v1_gateway_proto_rawDescGZIP() []byte {
	file_inference_v1_gateway_proto_rawDescOnce.Do(func() {
		file_inference_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_v1_gateway_proto_rawDesc), len(file_inference_v1_gateway_proto_rawDesc)))
	})
	return file_inference_v1_gateway_proto_rawDescData
}

var file_inference_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_inference_v1_gateway_proto_goTypes = []any{
	(*EvaluateRulesRequest)(nil),      // 0: gateway.v1.EvaluateRulesRequest
	(*EvaluateRulesResponse)(nil),     // 1: gateway.v1.EvaluateRulesResponse
	(*EvaluateRulesDiffRequest)(nil),  // 2: gateway.v1.EvaluateRulesDiffRequest
	(*EvaluateRulesDiffResponse)(nil), // 3: gateway.v1.EvaluateRulesDiffResponse
	(*RulesDiffSummary)(nil),          // 4: gateway.v1.RulesDiffSummary
	(*RuleSet)(nil),                   // 5: gateway.v1.RuleSet
	(*Explanation)(nil),               // 6: gateway.v1.Explanation
	(*Conflict)(nil),                  // 7: gateway.v1.Conflict
	(*structpb.Struct)(nil),           // 8: google.protobuf.Struct
	(*v1.Rule)(nil),                   // 9: crud.v1.Rule
}
var file_inference_v1_gateway_proto_depIdxs = []int32{
	8,  // 0: gateway.v1.EvaluateRulesRequest.features:type_name -> google.protobuf.Struct
	5,  // 1: gateway.v1.EvaluateRulesRequest.ruleset:type_name -> gateway.v1.RuleSet
	6,  // 2: gateway.v1.EvaluateRulesResponse.explanations:type_name -> gateway.v1.Explanation
	6,  // 3: gateway.v1.EvaluateRulesResponse.shadow_explanations:type_name -> gateway.v1.Explanation
	7,  // 4: gateway.v1.EvaluateRulesResponse.warnings:type_name -> gateway.v1.Conflict
	8,  // 5: gateway.v1.EvaluateRulesDiffRequest.features:type_name -> google.protobuf.Struct
	5,  // 6: gateway.v1.EvaluateRulesDiffRequest.ruleset_a:type_name -> gateway.v1.RuleSet
	5,  // 7: gateway.v1.EvaluateRulesDiffRequest.ruleset_b:type_name -> gateway.v1.RuleSet
	1,  // 8: gateway.v1.EvaluateRulesDiffResponse.a:type_name -> gateway.v1.EvaluateRulesResponse
	1,  // 9: gateway.v1.EvaluateRulesDiffResponse.b:type_name -> gateway.v1.EvaluateRulesResponse
	4,  // 10: gateway.v1.EvaluateRulesDiffResponse.diff:type_name -> gateway.v1.RulesDiffSummary
	9,  // 11: gateway.v1.RuleSet.rules:type_name -> crud.v1.Rule
	0,  // 12: gateway.v1.GatewayService.EvaluateRules:input_type -> gateway.v1.EvaluateRulesRequest
	2,  // 13: gateway.v1.GatewayService.EvaluateRulesDiff:input_type -> gateway.v1.EvaluateRulesDiffRequest
	1,  // 14: gateway.v1.GatewayService.EvaluateRules:output_type -> gateway.v1.EvaluateRulesResponse
	3,  // 15: gateway.v1.GatewayService.EvaluateRulesDiff:output_type -> gateway.v1.EvaluateRulesDiffResponse
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_inference_v1_gateway_proto_init() }
func file_inference_v1_gateway_proto_init() {
	if File_inference_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_v1_gateway_proto_rawDesc), len(file_inference_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_v1_gateway_proto_goTypes,
		DependencyIndexes: file_inference_v1_gateway_proto_depIdxs,
		MessageInfos:      file_inference_v1_gateway_proto_msgTypes,
	}.Build()
	File_inference_v1_gateway_proto = out.File
	file_inference_v1_gateway_proto_goTypes = nil
	file_inference_v1_gateway_proto_depIdxs = nil
}
