// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: training/v1/training.proto

package trainingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClearDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearDataRequest) Reset() {
	*x = ClearDataRequest{}
	mi := &file_training_v1_training_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearDataRequest) ProtoMessage() {}

func (x *ClearDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_training_v1_training_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearDataRequest.ProtoReflect.Descriptor instead.
func (*ClearDataRequest) Descriptor() ([]byte, []int) {
	return file_training_v1_training_proto_rawDescGZIP(), []int{0}
}

type ClearDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TablesCleared []string               `protobuf:"bytes,2,rep,name=tables_cleared,json=tablesCleared,proto3" json:"tables_cleared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearDataResponse) Reset() {
	*x = ClearDataResponse{}
	mi := &file_training_v1_training_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearDataResponse) ProtoMessage() {}

func (x *ClearDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_training_v1_training_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearDataResponse.ProtoReflect.Descriptor instead.
func (*ClearDataResponse) Descriptor() ([]byte, []int) {
	return file_training_v1_training_proto_rawDescGZIP(), []int{1}
}

func (x *ClearDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClearDataResponse) GetTablesCleared() []string {
	if x != nil {
		return x.TablesCleared
	}
	return nil
}

type TrainRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	MaxDepth               int32                  `protobuf:"varint,1,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	TrainingWindowDays     int32                  `protobuf:"varint,2,opt,name=training_window_days,json=trainingWindowDays,proto3" json:"training_window_days,omitempty"`
	SelectedFeatureColumns []string               `protobuf:"bytes,3,rep,name=selected_feature_columns,json=selectedFeatureColumns,proto3" json:"selected_feature_columns,omitempty"`
	SplitConfig            *SplitConfig           `protobuf:"bytes,4,opt,name=split_config,json=splitConfig,proto3" json:"split_config,omitempty"`
	TuningConfig           *TuningConfig          `protobuf:"bytes,5,opt,name=tuning_config,json=tuningConfig,proto3" json:"tuning_config,omitempty"`
	NEstimators            int32                  `protobuf:"varint,6,opt,name=n_estimators,json=nEstimators,proto3" json:"n_estimators,omitempty"`
	LearningRate           float32                `protobuf:"fixed32,7,opt,name=learning_rate,json=learningRate,proto3" json:"learning_rate,omitempty"`
	MinChildWeight         int32                  `protobuf:"varint,8,opt,name=min_child_weight,json=minChildWeight,proto3" json:"min_child_weight,omitempty"`
	Subsample              float32                `protobuf:"fixed32,9,opt,name=subsample,proto3" json:"subsample,omitempty"`
	ColsampleBytree        float32                `protobuf:"fixed32,10,opt,name=colsample_bytree,json=colsampleBytree,proto3" json:"colsample_bytree,omitempty"`
	Gamma                  float32                `protobuf:"fixed32,11,opt,name=gamma,proto3" json:"gamma,omitempty"`
	RegAlpha               float32                `protobuf:"fixed32,12,opt,name=reg_alpha,json=regAlpha,proto3" json:"reg_alpha,omitempty"`
	RegLambda              float32                `protobuf:"fixed32,13,opt,name=reg_lambda,json=regLambda,proto3" json:"reg_lambda,omitempty"`
	RandomState            int32                  `protobuf:"varint,14,opt,name=random_state,json=randomState,proto3" json:"random_state,omitempty"`
	EarlyStoppingRounds    *int32                 `protobuf:"varint,15,opt,name=early_stopping_rounds,json=earlyStoppingRounds,proto3,oneof" json:"early_stopping_rounds,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TrainRequest) Reset() {
	*x = TrainRequest{}
	mi := &file_training_v1_training_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainRequest) ProtoMessage() {}

func (x *TrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_training_v1_training_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainRequest.ProtoReflect.Descriptor instead.
func (*TrainRequest) Descriptor() ([]byte, []int) {
	return file_training_v1_training_proto_rawDescGZIP(), []int{2}
}

func (x *TrainRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *TrainRequest) GetTrainingWindowDays() int32 {
	if x != nil {
		return x.TrainingWindowDays
	}
	return 0
}

func (x *TrainRequest) GetSelectedFeatureColumns() []string {
	if x != nil {
		return x.SelectedFeatureColumns
	}
	return nil
}

func (x *TrainRequest) GetSplitConfig() *SplitConfig {
	if x != nil {
		return x.SplitConfig
	}
	return nil
}

func (x *TrainRequest) GetTuningConfig() *TuningConfig {
	if x != nil {
		return x.TuningConfig
	}
	return nil
}

func (x *TrainRequest) GetNEstimators() int32 {
	if x != nil {
		return x.NEstimators
	}
	return 0
}

func (x *TrainRequest) GetLearningRate() float32 {
	if x != nil {
		return x.LearningRate
	}
	return 0
}

func (x *TrainRequest) GetMinChildWeight() int32 {
	if x != nil {
		return x.MinChildWeight
	}
	return 0
}

func (x *TrainRequest) GetSubsample() float32 {
	if x != nil {
		return x.Subsample
	}
	return 0
}

func (x *TrainRequest) GetColsampleBytree() float32 {
	if x != nil {
		return x.ColsampleBytree
	}
	return 0
}

func (x *TrainRequest) GetGamma() float32 {
	if x != nil {
		return x.Gamma
	}
	return 0
}

func (x *TrainRequest) GetRegAlpha() float32 {
	if x != nil {
		return x.RegAlpha
	}
	return 0
}

func (x *TrainRequest) GetRegLambda() float32 {
	if x != nil {
		return x.RegLambda
	}
	return 0
}

func (x *TrainRequest) GetRandomState() int32 {
	if x != nil {
		return x.RandomState
	}
	return 0
}

func (x *TrainRequest) GetEarlyStoppingRounds() int32 {
	if x != nil && x.EarlyStoppingRounds != nil {
		return *x.EarlyStoppingRounds
	}
	return 0
}

type SplitConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Strategy           string                 `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"` // temporal, temporal_stratified, etc.
	NFolds             int32                  `protobuf:"varint,2,opt,name=n_folds,json=nFolds,proto3" json:"n_folds,omitempty"`
	StratifyColumn     *string                `protobuf:"bytes,3,opt,name=stratify_column,json=stratifyColumn,proto3,oneof" json:"stratify_column,omitempty"`
	GroupColumn        string                 `protobuf:"bytes,4,opt,name=group_column,json=groupColumn,proto3" json:"group_column,omitempty"`
	ValidationFraction float32                `protobuf:"fixed32,5,opt,name=validation_fraction,json=validationFraction,proto3" json:"validation_fraction,omitempty"`
	Seed               int32                  `protobuf:"varint,6,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SplitConfig) Reset() {
	*x = SplitConfig{}
	mi := &file_training_v1_training_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitConfig) ProtoMessage() {}

func (x *SplitConfig) ProtoReflect() protoreflect.Message {
	mi := &file_training_v1_training_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitConfig.ProtoReflect.Descriptor instead.
func (*SplitConfig) Descriptor() ([]byte, []int) {
	return file_training_v1_training_proto_rawDescGZIP(), []int{3}
}

func (x *SplitConfig) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *SplitConfig) GetNFolds() int32 {
	if x != nil {
		return x.NFolds
	}
	return 0
}

func (x *SplitConfig) GetStratifyColumn() string {
	if x != nil && x.StratifyColumn != nil {
		return *x.StratifyColumn
	}
	return ""
}

func (x *SplitConfig) GetGroupColumn() string {
	if x != nil {
		return x.GroupColumn
	}
	return ""
}

func (x *SplitConfig) GetValidationFraction() float32 {
	if x != nil {
		return x.ValidationFraction
	}
	return 0
}

func (x *SplitConfig) GetSeed() int32 {
	if x != nil {
		return x.Seed
	}
	return 0
}

type TuningConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Enabled             bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Strategy            string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"` // grid, random, bayesian
	NTrials             int32                  `protobuf:"varint,3,opt,name=n_trials,json=nTrials,proto3" json:"n_trials,omitempty"`
	TimeoutMinutes      int32                  `protobuf:"varint,4,opt,name=timeout_minutes,json=timeoutMinutes,proto3" json:"timeout_minutes,omitempty"`
	Metric              string                 `protobuf:"bytes,5,opt,name=metric,proto3" json:"metric,omitempty"`
	Direction           string                 `protobuf:"bytes,6,opt,name=direction,proto3" json:"direction,omitempty"` // maximize, minimize
	SelectedTrialNumber *int32                 `protobuf:"varint,7,opt,name=selected_trial_number,json=selectedTrialNumber,proto3,oneof" json:"selected_trial_number,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TuningConfig) Reset() {
	*x = TuningConfig{}
	mi := &file_training_v1_training_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TuningConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuningConfig) ProtoMessage() {}

func (x *TuningConfig) ProtoReflect() protoreflect.Message {
	mi := &file_training_v1_training_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuningConfig.ProtoReflect.Descriptor instead.
func (*TuningConfig) Descriptor() ([]byte, []int) {
	return file_training_v1_training_proto_rawDescGZIP(), []int{4}
}

func (x *TuningConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *TuningConfig) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *TuningConfig) GetNTrials() int32 {
	if x != nil {
		return x.NTrials
	}
	return 0
}

func (x *TuningConfig) GetTimeoutMinutes() int32 {
	if x != nil {
		return x.TimeoutMinutes
	}
	return 0
}

func (x *TuningConfig) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *TuningConfig) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *TuningConfig) GetSelectedTrialNumber() int32 {
	if x != nil && x.SelectedTrialNumber != nil {
		return *x.SelectedTrialNumber
	}
	return 0
}

type TrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainResponse) Reset() {
	*x = TrainResponse{}
	mi := &file_training_v1_training_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainResponse) ProtoMessage() {}

func (x *TrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_training_v1_training_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainResponse.ProtoReflect.Descriptor instead.
func (*TrainResponse) Descriptor() ([]byte, []int) {
	return file_training_v1_training_proto_rawDescGZIP(), []int{5}
}

func (x *TrainResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TrainResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TrainResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_training_v1_training_proto protoreflect.FileDescriptor

const file_training_v1_training_proto_rawDesc = "" +
	"\n" +
	"\x1atraining/v1/training.proto\x12\vtraining.v1\"\x12\n" +
	"\x10ClearDataRequest\"T\n" +
	"\x11ClearDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0etables_cleared\x18\x02 \x03(\tR\rtablesCleared\"\x97\x05\n" +
	"\fTrainRequest\x12\x1b\n" +
	"\tmax_depth\x18\x01 \x01(\x05R\bmaxDepth\x120\n" +
	"\x14training_window_days\x18\x02 \x01(\x05R\x12trainingWindowDays\x128\n" +
	"\x18selected_feature_columns\x18\x03 \x03(\tR\x16selectedFeatureColumns\x12;\n" +
	"\fsplit_config\x18\x04 \x01(\v2\x18.training.v1.SplitConfigR\vsplitConfig\x12>\n" +
	"\rtuning_config\x18\x05 \x01(\v2\x19.training.v1.TuningConfigR\ftuningConfig\x12!\n" +
	"\fn_estimators\x18\x06 \x01(\x05R\vnEstimators\x12#\n" +
	"\rlearning_rate\x18\a \x01(\x02R\flearningRate\x12(\n" +
	"\x10min_child_weight\x18\b \x01(\x05R\x0eminChildWeight\x12\x1c\n" +
	"\tsubsample\x18\t \x01(\x02R\tsubsample\x12)\n" +
	"\x10colsample_bytree\x18\n" +
	" \x01(\x02R\x0fcolsampleBytree\x12\x14\n" +
	"\x05gamma\x18\v \x01(\x02R\x05gamma\x12\x1b\n" +
	"\treg_alpha\x18\f \x01(\x02R\bregAlpha\x12\x1d\n" +
	"\n" +
	"reg_lambda\x18\r \x01(\x02R\tregLambda\x12!\n" +
	"\frandom_state\x18\x0e \x01(\x05R\vrandomState\x127\n" +
	"\x15early_stopping_rounds\x18\x0f \x01(\x05H\x00R\x13earlyStoppingRounds\x88\x01\x01B\x18\n" +
	"\x16_early_stopping_rounds\"\xec\x01\n" +
	"\vSplitConfig\x12\x1a\n" +
	"\bstrategy\x18\x01 \x01(\tR\bstrategy\x12\x17\n" +
	"\an_folds\x18\x02 \x01(\x05R\x06nFolds\x12,\n" +
	"\x0fstratify_column\x18\x03 \x01(\tH\x00R\x0estratifyColumn\x88\x01\x01\x12!\n" +
	"\fgroup_column\x18\x04 \x01(\tR\vgroupColumn\x12/\n" +
	"\x13validation_fraction\x18\x05 \x01(\x02R\x12validationFraction\x12\x12\n" +
	"\x04seed\x18\x06 \x01(\x05R\x04seedB\x12\n" +
	"\x10_stratify_column\"\x91\x02\n" +
	"\fTuningConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy\x12\x19\n" +
	"\bn_trials\x18\x03 \x01(\x05R\anTrials\x12'\n" +
	"\x0ftimeout_minutes\x18\x04 \x01(\x05R\x0etimeoutMinutes\x12\x16\n" +
	"\x06metric\x18\x05 \x01(\tR\x06metric\x12\x1c\n" +
	"\tdirection\x18\x06 \x01(\tR\tdirection\x127\n" +
	"\x15selected_trial_number\x18\a \x01(\x05H\x00R\x13selectedTrialNumber\x88\x01\x01B\x18\n" +
	"\x16_selected_trial_number\"V\n" +
	"\rTrainResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\x9d\x01\n" +
	"\x0fTrainingService\x12J\n" +
	"\tClearData\x12\x1d.training.v1.ClearDataRequest\x1a\x1e.training.v1.ClearDataResponse\x12>\n" +
	"\x05Train\x12\x19.training.v1.TrainRequest\x1a\x1a.training.v1.TrainResponseBJZHgithub.com/jonkmatsumo/label-lag/go/training/proto/trainingv1;trainingv1b\x06proto3"

var (
	file_training_v1_training_proto_rawDescOnce sync.Once
	file_training_v1_training_proto_rawDescData []byte
)

func file_training_v1_training_proto_rawDescGZIP() []byte {
	file_training_v1_training_proto_rawDescOnce.Do(func() {
		file_training_v1_training_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_training_v1_training_proto_rawDesc), len(file_training_v1_training_proto_rawDesc)))
	})
	return file_training_v1_training_proto_rawDescData
}

var file_training_v1_training_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_training_v1_training_proto_goTypes = []any{
	(*ClearDataRequest)(nil),  // 0: training.v1.ClearDataRequest
	(*ClearDataResponse)(nil), // 1: training.v1.ClearDataResponse
	(*TrainRequest)(nil),      // 2: training.v1.TrainRequest
	(*SplitConfig)(nil),       // 3: training.v1.SplitConfig
	(*TuningConfig)(nil),      // 4: training.v1.TuningConfig
	(*TrainResponse)(nil),     // 5: training.v1.TrainResponse
}
var file_training_v1_training_proto_depIdxs = []int32{
	3, // 0: training.v1.TrainRequest.split_config:type_name -> training.v1.SplitConfig
	4, // 1: training.v1.TrainRequest.tuning_config:type_name -> training.v1.TuningConfig
	0, // 2: training.v1.TrainingService.ClearData:input_type -> training.v1.ClearDataRequest
	2, // 3: training.v1.TrainingService.Train:input_type -> training.v1.TrainRequest
	1, // 4: training.v1.TrainingService.ClearData:output_type -> training.v1.ClearDataResponse
	5, // 5: training.v1.TrainingService.Train:output_type -> training.v1.TrainResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_training_v1_training_proto_init() }
func file_training_v1_training_proto_init() {
	if File_training_v1_training_proto != nil {
		return
	}
	file_training_v1_training_proto_msgTypes[2].OneofWrappers = []any{}
	file_training_v1_training_proto_msgTypes[3].OneofWrappers = []any{}
	file_training_v1_training_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_training_v1_training_proto_rawDesc), len(file_training_v1_training_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_training_v1_training_proto_goTypes,
		DependencyIndexes: file_training_v1_training_proto_depIdxs,
		MessageInfos:      file_training_v1_training_proto_msgTypes,
	}.Build()
	File_training_v1_training_proto = out.File
	file_training_v1_training_proto_goTypes = nil
	file_training_v1_training_proto_depIdxs = nil
}
