# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from go.inference.proto.gateway.v1 import gateway_pb2 as go_dot_inference_dot_proto_dot_gateway_dot_v1_dot_gateway__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in go/inference/proto/gateway/v1/gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvaluateRules = channel.unary_unary(
                '/gateway.v1.GatewayService/EvaluateRules',
                request_serializer=go_dot_inference_dot_proto_dot_gateway_dot_v1_dot_gateway__pb2.EvaluateRulesRequest.SerializeToString,
                response_deserializer=go_dot_inference_dot_proto_dot_gateway_dot_v1_dot_gateway__pb2.EvaluateRulesResponse.FromString,
                _registered_method=True)
        self.EvaluateRulesDiff = channel.unary_unary(
                '/gateway.v1.GatewayService/EvaluateRulesDiff',
                request_serializer=go_dot_inference_dot_proto_dot_gateway_dot_v1_dot_gateway__pb2.EvaluateRulesDiffRequest.SerializeToString,
                response_deserializer=go_dot_inference_dot_proto_dot_gateway_dot_v1_dot_gateway__pb2.EvaluateRulesDiffResponse.FromString,
                _registered_method=True)


class GatewayServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EvaluateRules(self, request, context):
        """Evaluates a set of rules against provided features.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateRulesDiff(self, request, context):
        """Compares two rulesets against provided features.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvaluateRules': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateRules,
                    request_deserializer=go_dot_inference_dot_proto_dot_gateway_dot_v1_dot_gateway__pb2.EvaluateRulesRequest.FromString,
                    response_serializer=go_dot_inference_dot_proto_dot_gateway_dot_v1_dot_gateway__pb2.EvaluateRulesResponse.SerializeToString,
            ),
            'EvaluateRulesDiff': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateRulesDiff,
                    request_deserializer=go_dot_inference_dot_proto_dot_gateway_dot_v1_dot_gateway__pb2.EvaluateRulesDiffRequest.FromString,
                    response_serializer=go_dot_inference_dot_proto_dot_gateway_dot_v1_dot_gateway__pb2.EvaluateRulesDiffResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gateway.v1.GatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gateway.v1.GatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EvaluateRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.v1.GatewayService/EvaluateRules',
            go_dot_inference_dot_proto_dot_gateway_dot_v1_dot_gateway__pb2.EvaluateRulesRequest.SerializeToString,
            go_dot_inference_dot_proto_dot_gateway_dot_v1_dot_gateway__pb2.EvaluateRulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateRulesDiff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.v1.GatewayService/EvaluateRulesDiff',
            go_dot_inference_dot_proto_dot_gateway_dot_v1_dot_gateway__pb2.EvaluateRulesDiffRequest.SerializeToString,
            go_dot_inference_dot_proto_dot_gateway_dot_v1_dot_gateway__pb2.EvaluateRulesDiffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
