// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: forecast/v1/forecast.proto

package forecastv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ForecastService_GetHealth_FullMethodName            = "/forecast.v1.ForecastService/GetHealth"
	ForecastService_GetDriftMonitoring_FullMethodName   = "/forecast.v1.ForecastService/GetDriftMonitoring"
	ForecastService_GetScoreDistribution_FullMethodName = "/forecast.v1.ForecastService/GetScoreDistribution"
	ForecastService_ReloadModel_FullMethodName          = "/forecast.v1.ForecastService/ReloadModel"
	ForecastService_DeployModel_FullMethodName          = "/forecast.v1.ForecastService/DeployModel"
)

// ForecastServiceClient is the client API for ForecastService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ForecastServiceClient interface {
	// Retrieves health status of the service.
	GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error)
	// Retrieves drift monitoring metrics.
	GetDriftMonitoring(ctx context.Context, in *GetDriftMonitoringRequest, opts ...grpc.CallOption) (*GetDriftMonitoringResponse, error)
	// Retrieves score distribution for monitoring.
	GetScoreDistribution(ctx context.Context, in *GetScoreDistributionRequest, opts ...grpc.CallOption) (*GetScoreDistributionResponse, error)
	// Reloads the production model from the model registry.
	ReloadModel(ctx context.Context, in *ReloadModelRequest, opts ...grpc.CallOption) (*ReloadModelResponse, error)
	// Deploys a specific model version to production.
	DeployModel(ctx context.Context, in *DeployModelRequest, opts ...grpc.CallOption) (*DeployModelResponse, error)
}

type forecastServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewForecastServiceClient(cc grpc.ClientConnInterface) ForecastServiceClient {
	return &forecastServiceClient{cc}
}

func (c *forecastServiceClient) GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHealthResponse)
	err := c.cc.Invoke(ctx, ForecastService_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forecastServiceClient) GetDriftMonitoring(ctx context.Context, in *GetDriftMonitoringRequest, opts ...grpc.CallOption) (*GetDriftMonitoringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDriftMonitoringResponse)
	err := c.cc.Invoke(ctx, ForecastService_GetDriftMonitoring_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forecastServiceClient) GetScoreDistribution(ctx context.Context, in *GetScoreDistributionRequest, opts ...grpc.CallOption) (*GetScoreDistributionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScoreDistributionResponse)
	err := c.cc.Invoke(ctx, ForecastService_GetScoreDistribution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forecastServiceClient) ReloadModel(ctx context.Context, in *ReloadModelRequest, opts ...grpc.CallOption) (*ReloadModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadModelResponse)
	err := c.cc.Invoke(ctx, ForecastService_ReloadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forecastServiceClient) DeployModel(ctx context.Context, in *DeployModelRequest, opts ...grpc.CallOption) (*DeployModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployModelResponse)
	err := c.cc.Invoke(ctx, ForecastService_DeployModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForecastServiceServer is the server API for ForecastService service.
// All implementations must embed UnimplementedForecastServiceServer
// for forward compatibility.
type ForecastServiceServer interface {
	// Retrieves health status of the service.
	GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error)
	// Retrieves drift monitoring metrics.
	GetDriftMonitoring(context.Context, *GetDriftMonitoringRequest) (*GetDriftMonitoringResponse, error)
	// Retrieves score distribution for monitoring.
	GetScoreDistribution(context.Context, *GetScoreDistributionRequest) (*GetScoreDistributionResponse, error)
	// Reloads the production model from the model registry.
	ReloadModel(context.Context, *ReloadModelRequest) (*ReloadModelResponse, error)
	// Deploys a specific model version to production.
	DeployModel(context.Context, *DeployModelRequest) (*DeployModelResponse, error)
	mustEmbedUnimplementedForecastServiceServer()
}

// UnimplementedForecastServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForecastServiceServer struct{}

func (UnimplementedForecastServiceServer) GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedForecastServiceServer) GetDriftMonitoring(context.Context, *GetDriftMonitoringRequest) (*GetDriftMonitoringResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDriftMonitoring not implemented")
}
func (UnimplementedForecastServiceServer) GetScoreDistribution(context.Context, *GetScoreDistributionRequest) (*GetScoreDistributionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScoreDistribution not implemented")
}
func (UnimplementedForecastServiceServer) ReloadModel(context.Context, *ReloadModelRequest) (*ReloadModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadModel not implemented")
}
func (UnimplementedForecastServiceServer) DeployModel(context.Context, *DeployModelRequest) (*DeployModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeployModel not implemented")
}
func (UnimplementedForecastServiceServer) mustEmbedUnimplementedForecastServiceServer() {}
func (UnimplementedForecastServiceServer) testEmbeddedByValue()                         {}

// UnsafeForecastServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForecastServiceServer will
// result in compilation errors.
type UnsafeForecastServiceServer interface {
	mustEmbedUnimplementedForecastServiceServer()
}

func RegisterForecastServiceServer(s grpc.ServiceRegistrar, srv ForecastServiceServer) {
	// If the following call panics, it indicates UnimplementedForecastServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ForecastService_ServiceDesc, srv)
}

func _ForecastService_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForecastServiceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForecastService_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForecastServiceServer).GetHealth(ctx, req.(*GetHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForecastService_GetDriftMonitoring_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriftMonitoringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForecastServiceServer).GetDriftMonitoring(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForecastService_GetDriftMonitoring_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForecastServiceServer).GetDriftMonitoring(ctx, req.(*GetDriftMonitoringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForecastService_GetScoreDistribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScoreDistributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForecastServiceServer).GetScoreDistribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForecastService_GetScoreDistribution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForecastServiceServer).GetScoreDistribution(ctx, req.(*GetScoreDistributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForecastService_ReloadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForecastServiceServer).ReloadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForecastService_ReloadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForecastServiceServer).ReloadModel(ctx, req.(*ReloadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForecastService_DeployModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForecastServiceServer).DeployModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForecastService_DeployModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForecastServiceServer).DeployModel(ctx, req.(*DeployModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ForecastService_ServiceDesc is the grpc.ServiceDesc for ForecastService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForecastService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "forecast.v1.ForecastService",
	HandlerType: (*ForecastServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHealth",
			Handler:    _ForecastService_GetHealth_Handler,
		},
		{
			MethodName: "GetDriftMonitoring",
			Handler:    _ForecastService_GetDriftMonitoring_Handler,
		},
		{
			MethodName: "GetScoreDistribution",
			Handler:    _ForecastService_GetScoreDistribution_Handler,
		},
		{
			MethodName: "ReloadModel",
			Handler:    _ForecastService_ReloadModel_Handler,
		},
		{
			MethodName: "DeployModel",
			Handler:    _ForecastService_DeployModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "forecast/v1/forecast.proto",
}
