# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from training.v1 import training_pb2 as training_dot_v1_dot_training__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in training/v1/training_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrainingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClearData = channel.unary_unary(
                '/training.v1.TrainingService/ClearData',
                request_serializer=training_dot_v1_dot_training__pb2.ClearDataRequest.SerializeToString,
                response_deserializer=training_dot_v1_dot_training__pb2.ClearDataResponse.FromString,
                _registered_method=True)
        self.Train = channel.unary_unary(
                '/training.v1.TrainingService/Train',
                request_serializer=training_dot_v1_dot_training__pb2.TrainRequest.SerializeToString,
                response_deserializer=training_dot_v1_dot_training__pb2.TrainResponse.FromString,
                _registered_method=True)


class TrainingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClearData(self, request, context):
        """Clears all data from the database.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Train(self, request, context):
        """Initiates model training.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClearData': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearData,
                    request_deserializer=training_dot_v1_dot_training__pb2.ClearDataRequest.FromString,
                    response_serializer=training_dot_v1_dot_training__pb2.ClearDataResponse.SerializeToString,
            ),
            'Train': grpc.unary_unary_rpc_method_handler(
                    servicer.Train,
                    request_deserializer=training_dot_v1_dot_training__pb2.TrainRequest.FromString,
                    response_serializer=training_dot_v1_dot_training__pb2.TrainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'training.v1.TrainingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('training.v1.TrainingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrainingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClearData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/training.v1.TrainingService/ClearData',
            training_dot_v1_dot_training__pb2.ClearDataRequest.SerializeToString,
            training_dot_v1_dot_training__pb2.ClearDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/training.v1.TrainingService/Train',
            training_dot_v1_dot_training__pb2.TrainRequest.SerializeToString,
            training_dot_v1_dot_training__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
