// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: inference/v1/inference.proto

package inferencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScoreRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RequestId           string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId              string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount              float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency            string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	ClientTransactionId string                 `protobuf:"bytes,5,opt,name=client_transaction_id,json=clientTransactionId,proto3" json:"client_transaction_id,omitempty"`
	Context             *structpb.Struct       `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ScoreRequest) Reset() {
	*x = ScoreRequest{}
	mi := &file_inference_v1_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreRequest) ProtoMessage() {}

func (x *ScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreRequest.ProtoReflect.Descriptor instead.
func (*ScoreRequest) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{0}
}

func (x *ScoreRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ScoreRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ScoreRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ScoreRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ScoreRequest) GetClientTransactionId() string {
	if x != nil {
		return x.ClientTransactionId
	}
	return ""
}

func (x *ScoreRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

type ScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ModelScore    float64                `protobuf:"fixed64,2,opt,name=model_score,json=modelScore,proto3" json:"model_score,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	ModelLoaded   bool                   `protobuf:"varint,4,opt,name=model_loaded,json=modelLoaded,proto3" json:"model_loaded,omitempty"`
	FeaturesUsed  *structpb.Struct       `protobuf:"bytes,5,opt,name=features_used,json=featuresUsed,proto3" json:"features_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreResponse) Reset() {
	*x = ScoreResponse{}
	mi := &file_inference_v1_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreResponse) ProtoMessage() {}

func (x *ScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreResponse.ProtoReflect.Descriptor instead.
func (*ScoreResponse) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{1}
}

func (x *ScoreResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ScoreResponse) GetModelScore() float64 {
	if x != nil {
		return x.ModelScore
	}
	return 0
}

func (x *ScoreResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *ScoreResponse) GetModelLoaded() bool {
	if x != nil {
		return x.ModelLoaded
	}
	return false
}

func (x *ScoreResponse) GetFeaturesUsed() *structpb.Struct {
	if x != nil {
		return x.FeaturesUsed
	}
	return nil
}

type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_inference_v1_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_inference_v1_inference_proto protoreflect.FileDescriptor

const file_inference_v1_inference_proto_rawDesc = "" +
	"\n" +
	"\x1cinference/v1/inference.proto\x12\finference.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xe1\x01\n" +
	"\fScoreRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x122\n" +
	"\x15client_transaction_id\x18\x05 \x01(\tR\x13clientTransactionId\x121\n" +
	"\acontext\x18\x06 \x01(\v2\x17.google.protobuf.StructR\acontext\"\xd5\x01\n" +
	"\rScoreResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vmodel_score\x18\x02 \x01(\x01R\n" +
	"modelScore\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\x12!\n" +
	"\fmodel_loaded\x18\x04 \x01(\bR\vmodelLoaded\x12<\n" +
	"\rfeatures_used\x18\x05 \x01(\v2\x17.google.protobuf.StructR\ffeaturesUsed\";\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2T\n" +
	"\x10InferenceService\x12@\n" +
	"\x05Score\x12\x1a.inference.v1.ScoreRequest\x1a\x1b.inference.v1.ScoreResponseBgZegithub.com/jonkmatsumo/label-lag/src/services/inference-gateway/internal/grpc/inferencev1;inferencev1b\x06proto3"

var (
	file_inference_v1_inference_proto_rawDescOnce sync.Once
	file_inference_v1_inference_proto_rawDescData []byte
)

func file_inference_v1_inference_proto_rawDescGZIP() []byte {
	file_inference_v1_inference_proto_rawDescOnce.Do(func() {
		file_inference_v1_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_v1_inference_proto_rawDesc), len(file_inference_v1_inference_proto_rawDesc)))
	})
	return file_inference_v1_inference_proto_rawDescData
}

var file_inference_v1_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_inference_v1_inference_proto_goTypes = []any{
	(*ScoreRequest)(nil),    // 0: inference.v1.ScoreRequest
	(*ScoreResponse)(nil),   // 1: inference.v1.ScoreResponse
	(*ErrorDetail)(nil),     // 2: inference.v1.ErrorDetail
	(*structpb.Struct)(nil), // 3: google.protobuf.Struct
}
var file_inference_v1_inference_proto_depIdxs = []int32{
	3, // 0: inference.v1.ScoreRequest.context:type_name -> google.protobuf.Struct
	3, // 1: inference.v1.ScoreResponse.features_used:type_name -> google.protobuf.Struct
	0, // 2: inference.v1.InferenceService.Score:input_type -> inference.v1.ScoreRequest
	1, // 3: inference.v1.InferenceService.Score:output_type -> inference.v1.ScoreResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_inference_v1_inference_proto_init() }
func file_inference_v1_inference_proto_init() {
	if File_inference_v1_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_v1_inference_proto_rawDesc), len(file_inference_v1_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_v1_inference_proto_goTypes,
		DependencyIndexes: file_inference_v1_inference_proto_depIdxs,
		MessageInfos:      file_inference_v1_inference_proto_msgTypes,
	}.Build()
	File_inference_v1_inference_proto = out.File
	file_inference_v1_inference_proto_goTypes = nil
	file_inference_v1_inference_proto_depIdxs = nil
}
