# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/v1/pagination.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common/v1/pagination.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63ommon/v1/pagination.proto\x12\tcommon.v1\"2\n\x11\x43ursorPageRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06\x63ursor\x18\x02 \x01(\t\"G\n\x12\x43ursorPageResponse\x12\x13\n\x0bnext_cursor\x18\x01 \x01(\t\x12\x12\n\x05total\x18\x02 \x01(\x03H\x00\x88\x01\x01\x42\x08\n\x06_totalB>Z<github.com/jonkmatsumo/label-lag/go/common/proto/v1;commonv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.v1.pagination_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/jonkmatsumo/label-lag/go/common/proto/v1;commonv1'
  _globals['_CURSORPAGEREQUEST']._serialized_start=41
  _globals['_CURSORPAGEREQUEST']._serialized_end=91
  _globals['_CURSORPAGERESPONSE']._serialized_start=93
  _globals['_CURSORPAGERESPONSE']._serialized_end=164
# @@protoc_insertion_point(module_scope)
