# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.proto.proto.crud.v1 import analytics_pb2 as proto_dot_crud_dot_v1_dot_analytics__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/crud/v1/analytics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDailyStats = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetDailyStats',
                request_serializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetDailyStatsRequest.SerializeToString,
                response_deserializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetDailyStatsResponse.FromString,
                _registered_method=True)
        self.GetTransactionDetails = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetTransactionDetails',
                request_serializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetTransactionDetailsRequest.SerializeToString,
                response_deserializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetTransactionDetailsResponse.FromString,
                _registered_method=True)
        self.GetRecentAlerts = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetRecentAlerts',
                request_serializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetRecentAlertsRequest.SerializeToString,
                response_deserializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetRecentAlertsResponse.FromString,
                _registered_method=True)
        self.GetOverviewMetrics = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetOverviewMetrics',
                request_serializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetOverviewMetricsRequest.SerializeToString,
                response_deserializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetOverviewMetricsResponse.FromString,
                _registered_method=True)
        self.GetDatasetFingerprint = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetDatasetFingerprint',
                request_serializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetDatasetFingerprintRequest.SerializeToString,
                response_deserializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetDatasetFingerprintResponse.FromString,
                _registered_method=True)
        self.GetFeatureSample = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetFeatureSample',
                request_serializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetFeatureSampleRequest.SerializeToString,
                response_deserializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetFeatureSampleResponse.FromString,
                _registered_method=True)
        self.GetSchemaSummary = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetSchemaSummary',
                request_serializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetSchemaSummaryRequest.SerializeToString,
                response_deserializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetSchemaSummaryResponse.FromString,
                _registered_method=True)


class AnalyticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDailyStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecentAlerts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOverviewMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDatasetFingerprint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFeatureSample(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchemaSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDailyStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDailyStats,
                    request_deserializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetDailyStatsRequest.FromString,
                    response_serializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetDailyStatsResponse.SerializeToString,
            ),
            'GetTransactionDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionDetails,
                    request_deserializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetTransactionDetailsRequest.FromString,
                    response_serializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetTransactionDetailsResponse.SerializeToString,
            ),
            'GetRecentAlerts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecentAlerts,
                    request_deserializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetRecentAlertsRequest.FromString,
                    response_serializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetRecentAlertsResponse.SerializeToString,
            ),
            'GetOverviewMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOverviewMetrics,
                    request_deserializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetOverviewMetricsRequest.FromString,
                    response_serializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetOverviewMetricsResponse.SerializeToString,
            ),
            'GetDatasetFingerprint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatasetFingerprint,
                    request_deserializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetDatasetFingerprintRequest.FromString,
                    response_serializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetDatasetFingerprintResponse.SerializeToString,
            ),
            'GetFeatureSample': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeatureSample,
                    request_deserializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetFeatureSampleRequest.FromString,
                    response_serializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetFeatureSampleResponse.SerializeToString,
            ),
            'GetSchemaSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchemaSummary,
                    request_deserializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetSchemaSummaryRequest.FromString,
                    response_serializer=proto_dot_crud_dot_v1_dot_analytics__pb2.GetSchemaSummaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crud.v1.AnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crud.v1.AnalyticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDailyStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetDailyStats',
            proto_dot_crud_dot_v1_dot_analytics__pb2.GetDailyStatsRequest.SerializeToString,
            proto_dot_crud_dot_v1_dot_analytics__pb2.GetDailyStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransactionDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetTransactionDetails',
            proto_dot_crud_dot_v1_dot_analytics__pb2.GetTransactionDetailsRequest.SerializeToString,
            proto_dot_crud_dot_v1_dot_analytics__pb2.GetTransactionDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecentAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetRecentAlerts',
            proto_dot_crud_dot_v1_dot_analytics__pb2.GetRecentAlertsRequest.SerializeToString,
            proto_dot_crud_dot_v1_dot_analytics__pb2.GetRecentAlertsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOverviewMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetOverviewMetrics',
            proto_dot_crud_dot_v1_dot_analytics__pb2.GetOverviewMetricsRequest.SerializeToString,
            proto_dot_crud_dot_v1_dot_analytics__pb2.GetOverviewMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDatasetFingerprint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetDatasetFingerprint',
            proto_dot_crud_dot_v1_dot_analytics__pb2.GetDatasetFingerprintRequest.SerializeToString,
            proto_dot_crud_dot_v1_dot_analytics__pb2.GetDatasetFingerprintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFeatureSample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetFeatureSample',
            proto_dot_crud_dot_v1_dot_analytics__pb2.GetFeatureSampleRequest.SerializeToString,
            proto_dot_crud_dot_v1_dot_analytics__pb2.GetFeatureSampleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchemaSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetSchemaSummary',
            proto_dot_crud_dot_v1_dot_analytics__pb2.GetSchemaSummaryRequest.SerializeToString,
            proto_dot_crud_dot_v1_dot_analytics__pb2.GetSchemaSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
