# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import analytics_pb2 as crud_dot_v1_dot_analytics__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in crud/v1/analytics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDailyStats = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetDailyStats',
                request_serializer=crud_dot_v1_dot_analytics__pb2.GetDailyStatsRequest.SerializeToString,
                response_deserializer=crud_dot_v1_dot_analytics__pb2.GetDailyStatsResponse.FromString,
                _registered_method=True)
        self.GetTransactionDetails = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetTransactionDetails',
                request_serializer=crud_dot_v1_dot_analytics__pb2.GetTransactionDetailsRequest.SerializeToString,
                response_deserializer=crud_dot_v1_dot_analytics__pb2.GetTransactionDetailsResponse.FromString,
                _registered_method=True)
        self.SearchTransactions = channel.unary_unary(
                '/crud.v1.AnalyticsService/SearchTransactions',
                request_serializer=crud_dot_v1_dot_analytics__pb2.SearchTransactionsRequest.SerializeToString,
                response_deserializer=crud_dot_v1_dot_analytics__pb2.SearchTransactionsResponse.FromString,
                _registered_method=True)
        self.GetRecentAlerts = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetRecentAlerts',
                request_serializer=crud_dot_v1_dot_analytics__pb2.GetRecentAlertsRequest.SerializeToString,
                response_deserializer=crud_dot_v1_dot_analytics__pb2.GetRecentAlertsResponse.FromString,
                _registered_method=True)
        self.GetOverviewMetrics = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetOverviewMetrics',
                request_serializer=crud_dot_v1_dot_analytics__pb2.GetOverviewMetricsRequest.SerializeToString,
                response_deserializer=crud_dot_v1_dot_analytics__pb2.GetOverviewMetricsResponse.FromString,
                _registered_method=True)
        self.GetDatasetFingerprint = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetDatasetFingerprint',
                request_serializer=crud_dot_v1_dot_analytics__pb2.GetDatasetFingerprintRequest.SerializeToString,
                response_deserializer=crud_dot_v1_dot_analytics__pb2.GetDatasetFingerprintResponse.FromString,
                _registered_method=True)
        self.GetFeatureSample = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetFeatureSample',
                request_serializer=crud_dot_v1_dot_analytics__pb2.GetFeatureSampleRequest.SerializeToString,
                response_deserializer=crud_dot_v1_dot_analytics__pb2.GetFeatureSampleResponse.FromString,
                _registered_method=True)
        self.GetSchemaSummary = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetSchemaSummary',
                request_serializer=crud_dot_v1_dot_analytics__pb2.GetSchemaSummaryRequest.SerializeToString,
                response_deserializer=crud_dot_v1_dot_analytics__pb2.GetSchemaSummaryResponse.FromString,
                _registered_method=True)
        self.GetTrainingData = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetTrainingData',
                request_serializer=crud_dot_v1_dot_analytics__pb2.GetTrainingDataRequest.SerializeToString,
                response_deserializer=crud_dot_v1_dot_analytics__pb2.GetTrainingDataResponse.FromString,
                _registered_method=True)
        self.GetBacktestFeatures = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetBacktestFeatures',
                request_serializer=crud_dot_v1_dot_analytics__pb2.GetBacktestFeaturesRequest.SerializeToString,
                response_deserializer=crud_dot_v1_dot_analytics__pb2.GetBacktestFeaturesResponse.FromString,
                _registered_method=True)
        self.SaveBacktestResult = channel.unary_unary(
                '/crud.v1.AnalyticsService/SaveBacktestResult',
                request_serializer=crud_dot_v1_dot_analytics__pb2.SaveBacktestResultRequest.SerializeToString,
                response_deserializer=crud_dot_v1_dot_analytics__pb2.SaveBacktestResultResponse.FromString,
                _registered_method=True)
        self.ListBacktestResults = channel.unary_unary(
                '/crud.v1.AnalyticsService/ListBacktestResults',
                request_serializer=crud_dot_v1_dot_analytics__pb2.ListBacktestResultsRequest.SerializeToString,
                response_deserializer=crud_dot_v1_dot_analytics__pb2.ListBacktestResultsResponse.FromString,
                _registered_method=True)
        self.GetBacktestResult = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetBacktestResult',
                request_serializer=crud_dot_v1_dot_analytics__pb2.GetBacktestResultRequest.SerializeToString,
                response_deserializer=crud_dot_v1_dot_analytics__pb2.GetBacktestResultResponse.FromString,
                _registered_method=True)
        self.GetDriftWindow = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetDriftWindow',
                request_serializer=crud_dot_v1_dot_analytics__pb2.GetDriftWindowRequest.SerializeToString,
                response_deserializer=crud_dot_v1_dot_analytics__pb2.GetDriftWindowResponse.FromString,
                _registered_method=True)


class AnalyticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDailyStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchTransactions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecentAlerts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOverviewMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDatasetFingerprint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFeatureSample(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchemaSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrainingData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBacktestFeatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveBacktestResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBacktestResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBacktestResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDriftWindow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDailyStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDailyStats,
                    request_deserializer=crud_dot_v1_dot_analytics__pb2.GetDailyStatsRequest.FromString,
                    response_serializer=crud_dot_v1_dot_analytics__pb2.GetDailyStatsResponse.SerializeToString,
            ),
            'GetTransactionDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionDetails,
                    request_deserializer=crud_dot_v1_dot_analytics__pb2.GetTransactionDetailsRequest.FromString,
                    response_serializer=crud_dot_v1_dot_analytics__pb2.GetTransactionDetailsResponse.SerializeToString,
            ),
            'SearchTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchTransactions,
                    request_deserializer=crud_dot_v1_dot_analytics__pb2.SearchTransactionsRequest.FromString,
                    response_serializer=crud_dot_v1_dot_analytics__pb2.SearchTransactionsResponse.SerializeToString,
            ),
            'GetRecentAlerts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecentAlerts,
                    request_deserializer=crud_dot_v1_dot_analytics__pb2.GetRecentAlertsRequest.FromString,
                    response_serializer=crud_dot_v1_dot_analytics__pb2.GetRecentAlertsResponse.SerializeToString,
            ),
            'GetOverviewMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOverviewMetrics,
                    request_deserializer=crud_dot_v1_dot_analytics__pb2.GetOverviewMetricsRequest.FromString,
                    response_serializer=crud_dot_v1_dot_analytics__pb2.GetOverviewMetricsResponse.SerializeToString,
            ),
            'GetDatasetFingerprint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatasetFingerprint,
                    request_deserializer=crud_dot_v1_dot_analytics__pb2.GetDatasetFingerprintRequest.FromString,
                    response_serializer=crud_dot_v1_dot_analytics__pb2.GetDatasetFingerprintResponse.SerializeToString,
            ),
            'GetFeatureSample': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeatureSample,
                    request_deserializer=crud_dot_v1_dot_analytics__pb2.GetFeatureSampleRequest.FromString,
                    response_serializer=crud_dot_v1_dot_analytics__pb2.GetFeatureSampleResponse.SerializeToString,
            ),
            'GetSchemaSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchemaSummary,
                    request_deserializer=crud_dot_v1_dot_analytics__pb2.GetSchemaSummaryRequest.FromString,
                    response_serializer=crud_dot_v1_dot_analytics__pb2.GetSchemaSummaryResponse.SerializeToString,
            ),
            'GetTrainingData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingData,
                    request_deserializer=crud_dot_v1_dot_analytics__pb2.GetTrainingDataRequest.FromString,
                    response_serializer=crud_dot_v1_dot_analytics__pb2.GetTrainingDataResponse.SerializeToString,
            ),
            'GetBacktestFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBacktestFeatures,
                    request_deserializer=crud_dot_v1_dot_analytics__pb2.GetBacktestFeaturesRequest.FromString,
                    response_serializer=crud_dot_v1_dot_analytics__pb2.GetBacktestFeaturesResponse.SerializeToString,
            ),
            'SaveBacktestResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveBacktestResult,
                    request_deserializer=crud_dot_v1_dot_analytics__pb2.SaveBacktestResultRequest.FromString,
                    response_serializer=crud_dot_v1_dot_analytics__pb2.SaveBacktestResultResponse.SerializeToString,
            ),
            'ListBacktestResults': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBacktestResults,
                    request_deserializer=crud_dot_v1_dot_analytics__pb2.ListBacktestResultsRequest.FromString,
                    response_serializer=crud_dot_v1_dot_analytics__pb2.ListBacktestResultsResponse.SerializeToString,
            ),
            'GetBacktestResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBacktestResult,
                    request_deserializer=crud_dot_v1_dot_analytics__pb2.GetBacktestResultRequest.FromString,
                    response_serializer=crud_dot_v1_dot_analytics__pb2.GetBacktestResultResponse.SerializeToString,
            ),
            'GetDriftWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDriftWindow,
                    request_deserializer=crud_dot_v1_dot_analytics__pb2.GetDriftWindowRequest.FromString,
                    response_serializer=crud_dot_v1_dot_analytics__pb2.GetDriftWindowResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crud.v1.AnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crud.v1.AnalyticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDailyStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetDailyStats',
            crud_dot_v1_dot_analytics__pb2.GetDailyStatsRequest.SerializeToString,
            crud_dot_v1_dot_analytics__pb2.GetDailyStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransactionDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetTransactionDetails',
            crud_dot_v1_dot_analytics__pb2.GetTransactionDetailsRequest.SerializeToString,
            crud_dot_v1_dot_analytics__pb2.GetTransactionDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/SearchTransactions',
            crud_dot_v1_dot_analytics__pb2.SearchTransactionsRequest.SerializeToString,
            crud_dot_v1_dot_analytics__pb2.SearchTransactionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecentAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetRecentAlerts',
            crud_dot_v1_dot_analytics__pb2.GetRecentAlertsRequest.SerializeToString,
            crud_dot_v1_dot_analytics__pb2.GetRecentAlertsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOverviewMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetOverviewMetrics',
            crud_dot_v1_dot_analytics__pb2.GetOverviewMetricsRequest.SerializeToString,
            crud_dot_v1_dot_analytics__pb2.GetOverviewMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDatasetFingerprint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetDatasetFingerprint',
            crud_dot_v1_dot_analytics__pb2.GetDatasetFingerprintRequest.SerializeToString,
            crud_dot_v1_dot_analytics__pb2.GetDatasetFingerprintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFeatureSample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetFeatureSample',
            crud_dot_v1_dot_analytics__pb2.GetFeatureSampleRequest.SerializeToString,
            crud_dot_v1_dot_analytics__pb2.GetFeatureSampleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchemaSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetSchemaSummary',
            crud_dot_v1_dot_analytics__pb2.GetSchemaSummaryRequest.SerializeToString,
            crud_dot_v1_dot_analytics__pb2.GetSchemaSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrainingData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetTrainingData',
            crud_dot_v1_dot_analytics__pb2.GetTrainingDataRequest.SerializeToString,
            crud_dot_v1_dot_analytics__pb2.GetTrainingDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBacktestFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetBacktestFeatures',
            crud_dot_v1_dot_analytics__pb2.GetBacktestFeaturesRequest.SerializeToString,
            crud_dot_v1_dot_analytics__pb2.GetBacktestFeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveBacktestResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/SaveBacktestResult',
            crud_dot_v1_dot_analytics__pb2.SaveBacktestResultRequest.SerializeToString,
            crud_dot_v1_dot_analytics__pb2.SaveBacktestResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBacktestResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/ListBacktestResults',
            crud_dot_v1_dot_analytics__pb2.ListBacktestResultsRequest.SerializeToString,
            crud_dot_v1_dot_analytics__pb2.ListBacktestResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBacktestResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetBacktestResult',
            crud_dot_v1_dot_analytics__pb2.GetBacktestResultRequest.SerializeToString,
            crud_dot_v1_dot_analytics__pb2.GetBacktestResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDriftWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetDriftWindow',
            crud_dot_v1_dot_analytics__pb2.GetDriftWindowRequest.SerializeToString,
            crud_dot_v1_dot_analytics__pb2.GetDriftWindowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
