# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from go.analytics.proto.crud.v1 import analytics_pb2 as go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in go/analytics/proto/crud/v1/analytics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDailyStats = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetDailyStats',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetDailyStatsRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetDailyStatsResponse.FromString,
                _registered_method=True)
        self.GetTransactionDetails = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetTransactionDetails',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetTransactionDetailsRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetTransactionDetailsResponse.FromString,
                _registered_method=True)
        self.SearchTransactions = channel.unary_unary(
                '/crud.v1.AnalyticsService/SearchTransactions',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.SearchTransactionsRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.SearchTransactionsResponse.FromString,
                _registered_method=True)
        self.GetRecentAlerts = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetRecentAlerts',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRecentAlertsRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRecentAlertsResponse.FromString,
                _registered_method=True)
        self.GetOverviewMetrics = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetOverviewMetrics',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetOverviewMetricsRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetOverviewMetricsResponse.FromString,
                _registered_method=True)
        self.GetDatasetFingerprint = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetDatasetFingerprint',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetDatasetFingerprintRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetDatasetFingerprintResponse.FromString,
                _registered_method=True)
        self.GetFeatureSample = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetFeatureSample',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetFeatureSampleRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetFeatureSampleResponse.FromString,
                _registered_method=True)
        self.GetSchemaSummary = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetSchemaSummary',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetSchemaSummaryRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetSchemaSummaryResponse.FromString,
                _registered_method=True)
        self.GetTrainingData = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetTrainingData',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetTrainingDataRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetTrainingDataResponse.FromString,
                _registered_method=True)
        self.GetBacktestFeatures = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetBacktestFeatures',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetBacktestFeaturesRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetBacktestFeaturesResponse.FromString,
                _registered_method=True)
        self.SaveBacktestResult = channel.unary_unary(
                '/crud.v1.AnalyticsService/SaveBacktestResult',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.SaveBacktestResultRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.SaveBacktestResultResponse.FromString,
                _registered_method=True)
        self.ListBacktestResults = channel.unary_unary(
                '/crud.v1.AnalyticsService/ListBacktestResults',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ListBacktestResultsRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ListBacktestResultsResponse.FromString,
                _registered_method=True)
        self.GetBacktestResult = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetBacktestResult',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetBacktestResultRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetBacktestResultResponse.FromString,
                _registered_method=True)
        self.GetDriftWindow = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetDriftWindow',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetDriftWindowRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetDriftWindowResponse.FromString,
                _registered_method=True)
        self.StoreGeneratedData = channel.unary_unary(
                '/crud.v1.AnalyticsService/StoreGeneratedData',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.StoreGeneratedDataRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.StoreGeneratedDataResponse.FromString,
                _registered_method=True)
        self.ClearAllData = channel.unary_unary(
                '/crud.v1.AnalyticsService/ClearAllData',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ClearAllDataRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ClearAllDataResponse.FromString,
                _registered_method=True)
        self.MaterializeFeatures = channel.unary_unary(
                '/crud.v1.AnalyticsService/MaterializeFeatures',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.MaterializeFeaturesRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.MaterializeFeaturesResponse.FromString,
                _registered_method=True)
        self.GenerateData = channel.unary_unary(
                '/crud.v1.AnalyticsService/GenerateData',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GenerateDataRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GenerateDataResponse.FromString,
                _registered_method=True)
        self.GetInferenceScores = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetInferenceScores',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetInferenceScoresRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetInferenceScoresResponse.FromString,
                _registered_method=True)
        self.SaveRule = channel.unary_unary(
                '/crud.v1.AnalyticsService/SaveRule',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.SaveRuleRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.SaveRuleResponse.FromString,
                _registered_method=True)
        self.GetRule = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetRule',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleResponse.FromString,
                _registered_method=True)
        self.ListRules = channel.unary_unary(
                '/crud.v1.AnalyticsService/ListRules',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ListRulesRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ListRulesResponse.FromString,
                _registered_method=True)
        self.DeleteRule = channel.unary_unary(
                '/crud.v1.AnalyticsService/DeleteRule',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.DeleteRuleRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.DeleteRuleResponse.FromString,
                _registered_method=True)
        self.ListRuleVersions = channel.unary_unary(
                '/crud.v1.AnalyticsService/ListRuleVersions',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ListRuleVersionsRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ListRuleVersionsResponse.FromString,
                _registered_method=True)
        self.GetRuleVersion = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetRuleVersion',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleVersionRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleVersionResponse.FromString,
                _registered_method=True)
        self.PublishRuleVersion = channel.unary_unary(
                '/crud.v1.AnalyticsService/PublishRuleVersion',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.PublishRuleVersionRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.PublishRuleVersionResponse.FromString,
                _registered_method=True)
        self.GetRuleReadiness = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetRuleReadiness',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleReadinessRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleReadinessResponse.FromString,
                _registered_method=True)
        self.DiffRuleVersions = channel.unary_unary(
                '/crud.v1.AnalyticsService/DiffRuleVersions',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.DiffRuleVersionsRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.DiffRuleVersionsResponse.FromString,
                _registered_method=True)
        self.GetRuleStats = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetRuleStats',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleStatsRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleStatsResponse.FromString,
                _registered_method=True)
        self.GetAttribution = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetAttribution',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetAttributionRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetAttributionResponse.FromString,
                _registered_method=True)
        self.LogInferenceEvent = channel.unary_unary(
                '/crud.v1.AnalyticsService/LogInferenceEvent',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.LogInferenceEventRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.LogInferenceEventResponse.FromString,
                _registered_method=True)
        self.GetLatestUserFeatures = channel.unary_unary(
                '/crud.v1.AnalyticsService/GetLatestUserFeatures',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetLatestUserFeaturesRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetLatestUserFeaturesResponse.FromString,
                _registered_method=True)
        self.BatchGetLatestUserFeatures = channel.unary_unary(
                '/crud.v1.AnalyticsService/BatchGetLatestUserFeatures',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.BatchGetLatestUserFeaturesRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.BatchGetLatestUserFeaturesResponse.FromString,
                _registered_method=True)
        self.CompareBacktests = channel.unary_unary(
                '/crud.v1.AnalyticsService/CompareBacktests',
                request_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.CompareBacktestsRequest.SerializeToString,
                response_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.CompareBacktestsResponse.FromString,
                _registered_method=True)


class AnalyticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDailyStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchTransactions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecentAlerts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOverviewMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDatasetFingerprint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFeatureSample(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchemaSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrainingData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBacktestFeatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveBacktestResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBacktestResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBacktestResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDriftWindow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreGeneratedData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearAllData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MaterializeFeatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateData(self, request, context):
        """Synthetic Data Generation (Go implementation)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInferenceScores(self, request, context):
        """Score Monitoring (C3)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveRule(self, request, context):
        """Rule Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRuleVersions(self, request, context):
        """Rule Versioning & Control Plane
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuleVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishRuleVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuleReadiness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiffRuleVersions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuleStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttribution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogInferenceEvent(self, request, context):
        """Inference Events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestUserFeatures(self, request, context):
        """Feature Hydration (Phase 6)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGetLatestUserFeatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompareBacktests(self, request, context):
        """Backtest Compare (Phase 8)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDailyStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDailyStats,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetDailyStatsRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetDailyStatsResponse.SerializeToString,
            ),
            'GetTransactionDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionDetails,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetTransactionDetailsRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetTransactionDetailsResponse.SerializeToString,
            ),
            'SearchTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchTransactions,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.SearchTransactionsRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.SearchTransactionsResponse.SerializeToString,
            ),
            'GetRecentAlerts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecentAlerts,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRecentAlertsRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRecentAlertsResponse.SerializeToString,
            ),
            'GetOverviewMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOverviewMetrics,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetOverviewMetricsRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetOverviewMetricsResponse.SerializeToString,
            ),
            'GetDatasetFingerprint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatasetFingerprint,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetDatasetFingerprintRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetDatasetFingerprintResponse.SerializeToString,
            ),
            'GetFeatureSample': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeatureSample,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetFeatureSampleRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetFeatureSampleResponse.SerializeToString,
            ),
            'GetSchemaSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchemaSummary,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetSchemaSummaryRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetSchemaSummaryResponse.SerializeToString,
            ),
            'GetTrainingData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingData,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetTrainingDataRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetTrainingDataResponse.SerializeToString,
            ),
            'GetBacktestFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBacktestFeatures,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetBacktestFeaturesRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetBacktestFeaturesResponse.SerializeToString,
            ),
            'SaveBacktestResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveBacktestResult,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.SaveBacktestResultRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.SaveBacktestResultResponse.SerializeToString,
            ),
            'ListBacktestResults': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBacktestResults,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ListBacktestResultsRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ListBacktestResultsResponse.SerializeToString,
            ),
            'GetBacktestResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBacktestResult,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetBacktestResultRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetBacktestResultResponse.SerializeToString,
            ),
            'GetDriftWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDriftWindow,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetDriftWindowRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetDriftWindowResponse.SerializeToString,
            ),
            'StoreGeneratedData': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreGeneratedData,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.StoreGeneratedDataRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.StoreGeneratedDataResponse.SerializeToString,
            ),
            'ClearAllData': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearAllData,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ClearAllDataRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ClearAllDataResponse.SerializeToString,
            ),
            'MaterializeFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.MaterializeFeatures,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.MaterializeFeaturesRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.MaterializeFeaturesResponse.SerializeToString,
            ),
            'GenerateData': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateData,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GenerateDataRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GenerateDataResponse.SerializeToString,
            ),
            'GetInferenceScores': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInferenceScores,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetInferenceScoresRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetInferenceScoresResponse.SerializeToString,
            ),
            'SaveRule': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveRule,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.SaveRuleRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.SaveRuleResponse.SerializeToString,
            ),
            'GetRule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRule,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleResponse.SerializeToString,
            ),
            'ListRules': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRules,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ListRulesRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ListRulesResponse.SerializeToString,
            ),
            'DeleteRule': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRule,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.DeleteRuleRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.DeleteRuleResponse.SerializeToString,
            ),
            'ListRuleVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRuleVersions,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ListRuleVersionsRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ListRuleVersionsResponse.SerializeToString,
            ),
            'GetRuleVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuleVersion,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleVersionRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleVersionResponse.SerializeToString,
            ),
            'PublishRuleVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishRuleVersion,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.PublishRuleVersionRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.PublishRuleVersionResponse.SerializeToString,
            ),
            'GetRuleReadiness': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuleReadiness,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleReadinessRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleReadinessResponse.SerializeToString,
            ),
            'DiffRuleVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.DiffRuleVersions,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.DiffRuleVersionsRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.DiffRuleVersionsResponse.SerializeToString,
            ),
            'GetRuleStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuleStats,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleStatsRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleStatsResponse.SerializeToString,
            ),
            'GetAttribution': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttribution,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetAttributionRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetAttributionResponse.SerializeToString,
            ),
            'LogInferenceEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.LogInferenceEvent,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.LogInferenceEventRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.LogInferenceEventResponse.SerializeToString,
            ),
            'GetLatestUserFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestUserFeatures,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetLatestUserFeaturesRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetLatestUserFeaturesResponse.SerializeToString,
            ),
            'BatchGetLatestUserFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGetLatestUserFeatures,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.BatchGetLatestUserFeaturesRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.BatchGetLatestUserFeaturesResponse.SerializeToString,
            ),
            'CompareBacktests': grpc.unary_unary_rpc_method_handler(
                    servicer.CompareBacktests,
                    request_deserializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.CompareBacktestsRequest.FromString,
                    response_serializer=go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.CompareBacktestsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crud.v1.AnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crud.v1.AnalyticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDailyStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetDailyStats',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetDailyStatsRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetDailyStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransactionDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetTransactionDetails',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetTransactionDetailsRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetTransactionDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/SearchTransactions',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.SearchTransactionsRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.SearchTransactionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecentAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetRecentAlerts',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRecentAlertsRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRecentAlertsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOverviewMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetOverviewMetrics',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetOverviewMetricsRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetOverviewMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDatasetFingerprint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetDatasetFingerprint',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetDatasetFingerprintRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetDatasetFingerprintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFeatureSample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetFeatureSample',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetFeatureSampleRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetFeatureSampleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchemaSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetSchemaSummary',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetSchemaSummaryRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetSchemaSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrainingData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetTrainingData',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetTrainingDataRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetTrainingDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBacktestFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetBacktestFeatures',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetBacktestFeaturesRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetBacktestFeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveBacktestResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/SaveBacktestResult',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.SaveBacktestResultRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.SaveBacktestResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBacktestResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/ListBacktestResults',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ListBacktestResultsRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ListBacktestResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBacktestResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetBacktestResult',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetBacktestResultRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetBacktestResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDriftWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetDriftWindow',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetDriftWindowRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetDriftWindowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreGeneratedData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/StoreGeneratedData',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.StoreGeneratedDataRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.StoreGeneratedDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearAllData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/ClearAllData',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ClearAllDataRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ClearAllDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MaterializeFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/MaterializeFeatures',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.MaterializeFeaturesRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.MaterializeFeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GenerateData',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GenerateDataRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GenerateDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInferenceScores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetInferenceScores',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetInferenceScoresRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetInferenceScoresResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/SaveRule',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.SaveRuleRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.SaveRuleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetRule',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/ListRules',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ListRulesRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ListRulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/DeleteRule',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.DeleteRuleRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.DeleteRuleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRuleVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/ListRuleVersions',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ListRuleVersionsRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.ListRuleVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuleVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetRuleVersion',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleVersionRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishRuleVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/PublishRuleVersion',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.PublishRuleVersionRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.PublishRuleVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuleReadiness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetRuleReadiness',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleReadinessRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleReadinessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiffRuleVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/DiffRuleVersions',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.DiffRuleVersionsRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.DiffRuleVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuleStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetRuleStats',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleStatsRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetRuleStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAttribution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetAttribution',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetAttributionRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetAttributionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LogInferenceEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/LogInferenceEvent',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.LogInferenceEventRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.LogInferenceEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestUserFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/GetLatestUserFeatures',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetLatestUserFeaturesRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.GetLatestUserFeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchGetLatestUserFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/BatchGetLatestUserFeatures',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.BatchGetLatestUserFeaturesRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.BatchGetLatestUserFeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompareBacktests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crud.v1.AnalyticsService/CompareBacktests',
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.CompareBacktestsRequest.SerializeToString,
            go_dot_analytics_dot_proto_dot_crud_dot_v1_dot_analytics__pb2.CompareBacktestsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
