# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference/v1/inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference/v1/inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cinference/v1/inference.proto\x12\x0cinference.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x9e\x01\n\x0cScoreRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t\x12\x1d\n\x15\x63lient_transaction_id\x18\x05 \x01(\t\x12(\n\x07\x63ontext\x18\x06 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x95\x01\n\rScoreResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x13\n\x0bmodel_score\x18\x02 \x01(\x01\x12\x15\n\rmodel_version\x18\x03 \x01(\t\x12\x14\n\x0cmodel_loaded\x18\x04 \x01(\x08\x12.\n\rfeatures_used\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct\",\n\x0b\x45rrorDetail\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2T\n\x10InferenceService\x12@\n\x05Score\x12\x1a.inference.v1.ScoreRequest\x1a\x1b.inference.v1.ScoreResponseBgZegithub.com/jonkmatsumo/label-lag/src/services/inference-gateway/internal/grpc/inferencev1;inferencev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.v1.inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Zegithub.com/jonkmatsumo/label-lag/src/services/inference-gateway/internal/grpc/inferencev1;inferencev1'
  _globals['_SCOREREQUEST']._serialized_start=77
  _globals['_SCOREREQUEST']._serialized_end=235
  _globals['_SCORERESPONSE']._serialized_start=238
  _globals['_SCORERESPONSE']._serialized_end=387
  _globals['_ERRORDETAIL']._serialized_start=389
  _globals['_ERRORDETAIL']._serialized_end=433
  _globals['_INFERENCESERVICE']._serialized_start=435
  _globals['_INFERENCESERVICE']._serialized_end=519
# @@protoc_insertion_point(module_scope)
